"""Generate Enka stat IDs from the same exported capture cache used by GOODCapture."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PROP_TYPE_MAP = {
    "FIGHT_PROP_HP": "hp",
    "FIGHT_PROP_HP_PERCENT": "hp_",
    "FIGHT_PROP_ATTACK": "atk",
    "FIGHT_PROP_ATTACK_PERCENT": "atk_",
    "FIGHT_PROP_DEFENSE": "def",
    "FIGHT_PROP_DEFENSE_PERCENT": "def_",
    "FIGHT_PROP_CRITICAL": "critRate_",
    "FIGHT_PROP_CRITICAL_HURT": "critDMG_",
    "FIGHT_PROP_CHARGE_EFFICIENCY": "enerRech_",
    "FIGHT_PROP_HEAL_ADD": "heal_",
    "FIGHT_PROP_ELEMENT_MASTERY": "eleMas",
    "FIGHT_PROP_PHYSICAL_ADD_HURT": "physical_dmg_",
    "FIGHT_PROP_FIRE_ADD_HURT": "pyro_dmg_",
    "FIGHT_PROP_ELEC_ADD_HURT": "electro_dmg_",
    "FIGHT_PROP_WATER_ADD_HURT": "hydro_dmg_",
    "FIGHT_PROP_WIND_ADD_HURT": "anemo_dmg_",
    "FIGHT_PROP_ICE_ADD_HURT": "cryo_dmg_",
    "FIGHT_PROP_ROCK_ADD_HURT": "geo_dmg_",
    "FIGHT_PROP_GRASS_ADD_HURT": "dendro_dmg_",
}

CACHE_PROPERTY_MAP = {
    "Hp": "hp",
    "HpPercent": "hp_",
    "Attack": "atk",
    "AttackPercent": "atk_",
    "Defense": "def",
    "DefensePercent": "def_",
    "CritRate": "critRate_",
    "CritDamage": "critDMG_",
    "EnergyRecharge": "enerRech_",
    "Healing": "heal_",
    "ElementalMastery": "eleMas",
    "PhysicalDamage": "physical_dmg_",
    "PyroDamage": "pyro_dmg_",
    "ElectroDamage": "electro_dmg_",
    "HydroDamage": "hydro_dmg_",
    "AnemoDamage": "anemo_dmg_",
    "CryoDamage": "cryo_dmg_",
    "GeoDamage": "geo_dmg_",
    "DendroDamage": "dendro_dmg_",
}


def generate_stat_map(cache: dict) -> dict[str, str]:
    # Names and entity IDs already come directly from game JSON in enkaFetcher.ts.
    # Fetching the old, unobfuscated AGD tables here would silently lose newer IDs.
    if not cache["property_map"] or not cache["affix_map"]:
        raise ValueError("Enka stat generation requires nonempty property_map and affix_map")
    result = dict(PROP_TYPE_MAP)
    for key, prop in cache["property_map"].items():
        result[str(key)] = CACHE_PROPERTY_MAP[prop]
    for key, entry in cache["affix_map"].items():
        result[str(key)] = CACHE_PROPERTY_MAP[entry["property"]]
    return result


def run(project_root: Path = ROOT) -> None:
    cache = json.loads(
        (project_root / "public" / "good" / "genshin_scanner_data.json").read_text("utf-8")
    )["capture"]
    stat_map = generate_stat_map(cache)
    output = project_root / "src" / "data" / "enkaIdMap.ts"
    lines = [
        "// Auto-generated by scripts/enka.py",
        "// Entity ID maps are read directly from game JSON by enkaFetcher.ts.",
        "",
        "export const statIdMap: Record<string, string> = {",
        *(f'  "{key}": {json.dumps(value)},' for key, value in sorted(stat_map.items())),
        "};",
        "",
    ]
    output.with_suffix(".ts.new").write_text("\n".join(lines), encoding="utf-8")
    output.with_suffix(".ts.new").replace(output)
    print(f"Generated {output}: {len(stat_map)} stat IDs")
