// This file is auto-generated by scripts/hakushin.py
// Do not edit this file directly

import type { CharacterStats } from './types';

export const charStats: Record<string, CharacterStats> = {
  "aino": {
    "Lv90": {
      "baseHp": "11201",
      "baseAtk": "242",
      "baseDef": "607",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "11976",
      "baseAtk": "304",
      "baseDef": "649",
      "em": "96"
    }
  },
  "albedo": {
    "Lv90": {
      "baseHp": "13226",
      "baseAtk": "251",
      "baseDef": "876",
      "em": "0",
      "geo%": "28.8%"
    },
    "Lv100": {
      "baseHp": "14166",
      "baseAtk": "308",
      "baseDef": "938",
      "em": "0",
      "geo%": "28.8%"
    }
  },
  "alhaitham": {
    "Lv90": {
      "baseHp": "13348",
      "baseAtk": "313",
      "baseDef": "782",
      "em": "0",
      "dendro%": "28.8%"
    },
    "Lv100": {
      "baseHp": "14297",
      "baseAtk": "384",
      "baseDef": "837",
      "em": "0",
      "dendro%": "28.8%"
    }
  },
  "aloy": {
    "Lv90": {
      "baseHp": "10899",
      "baseAtk": "234",
      "baseDef": "676",
      "em": "0",
      "cryo%": "28.8%"
    },
    "Lv100": {
      "baseHp": "11673",
      "baseAtk": "287",
      "baseDef": "724",
      "em": "0",
      "cryo%": "28.8%"
    }
  },
  "amber": {
    "Lv90": {
      "baseHp": "9461",
      "baseAtk": "223",
      "baseDef": "601",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10116",
      "baseAtk": "280",
      "baseDef": "642",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "arataki_itto": {
    "Lv90": {
      "baseHp": "12858",
      "baseAtk": "227",
      "baseDef": "959",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "13772",
      "baseAtk": "278",
      "baseDef": "1027",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "arlecchino": {
    "Lv90": {
      "baseHp": "13103",
      "baseAtk": "342",
      "baseDef": "765",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "14034",
      "baseAtk": "419",
      "baseDef": "819",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "baizhu": {
    "Lv90": {
      "baseHp": "13348",
      "baseAtk": "193",
      "baseDef": "500",
      "em": "0",
      "hp%": "28.8%"
    },
    "Lv100": {
      "baseHp": "14297",
      "baseAtk": "236",
      "baseDef": "535",
      "em": "0",
      "hp%": "28.8%"
    }
  },
  "barbara": {
    "Lv90": {
      "baseHp": "9787",
      "baseAtk": "159",
      "baseDef": "669",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10464",
      "baseAtk": "200",
      "baseDef": "715",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "beidou": {
    "Lv90": {
      "baseHp": "13050",
      "baseAtk": "225",
      "baseDef": "648",
      "em": "0",
      "electro%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13953",
      "baseAtk": "283",
      "baseDef": "693",
      "em": "0",
      "electro%": "24.0%"
    }
  },
  "bennett": {
    "Lv90": {
      "baseHp": "12397",
      "baseAtk": "191",
      "baseDef": "771",
      "em": "0",
      "er": "26.7%"
    },
    "Lv100": {
      "baseHp": "13255",
      "baseAtk": "240",
      "baseDef": "825",
      "em": "0",
      "er": "26.7%"
    }
  },
  "candace": {
    "Lv90": {
      "baseHp": "10875",
      "baseAtk": "212",
      "baseDef": "683",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11627",
      "baseAtk": "267",
      "baseDef": "730",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "charlotte": {
    "Lv90": {
      "baseHp": "10766",
      "baseAtk": "173",
      "baseDef": "546",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11511",
      "baseAtk": "217",
      "baseDef": "584",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "chasca": {
    "Lv90": {
      "baseHp": "9797",
      "baseAtk": "347",
      "baseDef": "615",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "10493",
      "baseAtk": "425",
      "baseDef": "659",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "chevreuse": {
    "Lv90": {
      "baseHp": "11962",
      "baseAtk": "193",
      "baseDef": "605",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "12790",
      "baseAtk": "243",
      "baseDef": "647",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "chiori": {
    "Lv90": {
      "baseHp": "11438",
      "baseAtk": "323",
      "baseDef": "953",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "12251",
      "baseAtk": "396",
      "baseDef": "1021",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "chongyun": {
    "Lv90": {
      "baseHp": "10984",
      "baseAtk": "223",
      "baseDef": "648",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11743",
      "baseAtk": "280",
      "baseDef": "693",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "citlali": {
    "Lv90": {
      "baseHp": "11634",
      "baseAtk": "127",
      "baseDef": "763",
      "em": "115"
    },
    "Lv100": {
      "baseHp": "12460",
      "baseAtk": "155",
      "baseDef": "817",
      "em": "115"
    }
  },
  "clorinde": {
    "Lv90": {
      "baseHp": "12956",
      "baseAtk": "337",
      "baseDef": "784",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "13877",
      "baseAtk": "413",
      "baseDef": "840",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "collei": {
    "Lv90": {
      "baseHp": "9787",
      "baseAtk": "200",
      "baseDef": "601",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10464",
      "baseAtk": "251",
      "baseDef": "642",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "columbina": {
    "Lv90": {
      "baseHp": "14695",
      "baseAtk": "96",
      "baseDef": "515",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "15740",
      "baseAtk": "117",
      "baseDef": "552",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "cyno": {
    "Lv90": {
      "baseHp": "12491",
      "baseAtk": "318",
      "baseDef": "859",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13379",
      "baseAtk": "390",
      "baseDef": "920",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "dahlia": {
    "Lv90": {
      "baseHp": "12506",
      "baseAtk": "189",
      "baseDef": "560",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13371",
      "baseAtk": "237",
      "baseDef": "598",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "dehya": {
    "Lv90": {
      "baseHp": "15675",
      "baseAtk": "265",
      "baseDef": "628",
      "em": "0",
      "hp%": "28.8%"
    },
    "Lv100": {
      "baseHp": "16789",
      "baseAtk": "325",
      "baseDef": "673",
      "em": "0",
      "hp%": "28.8%"
    }
  },
  "diluc": {
    "Lv90": {
      "baseHp": "12981",
      "baseAtk": "335",
      "baseDef": "784",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "13903",
      "baseAtk": "410",
      "baseDef": "840",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "diona": {
    "Lv90": {
      "baseHp": "9570",
      "baseAtk": "212",
      "baseDef": "601",
      "em": "0",
      "cryo%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10232",
      "baseAtk": "267",
      "baseDef": "642",
      "em": "0",
      "cryo%": "24.0%"
    }
  },
  "dori": {
    "Lv90": {
      "baseHp": "12397",
      "baseAtk": "223",
      "baseDef": "723",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13255",
      "baseAtk": "280",
      "baseDef": "774",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "durin": {
    "Lv90": {
      "baseHp": "12430",
      "baseAtk": "347",
      "baseDef": "822",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13313",
      "baseAtk": "425",
      "baseDef": "881",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "emilie": {
    "Lv90": {
      "baseHp": "13568",
      "baseAtk": "335",
      "baseDef": "730",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "14533",
      "baseAtk": "410",
      "baseDef": "782",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "escoffier": {
    "Lv90": {
      "baseHp": "13348",
      "baseAtk": "347",
      "baseDef": "732",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "14297",
      "baseAtk": "425",
      "baseDef": "784",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "eula": {
    "Lv90": {
      "baseHp": "13226",
      "baseAtk": "342",
      "baseDef": "751",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "14166",
      "baseAtk": "419",
      "baseDef": "804",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "faruzan": {
    "Lv90": {
      "baseHp": "9570",
      "baseAtk": "196",
      "baseDef": "628",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10232",
      "baseAtk": "247",
      "baseDef": "671",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "fischl": {
    "Lv90": {
      "baseHp": "9189",
      "baseAtk": "244",
      "baseDef": "594",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "9825",
      "baseAtk": "307",
      "baseDef": "635",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "flins": {
    "Lv90": {
      "baseHp": "12491",
      "baseAtk": "352",
      "baseDef": "809",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13379",
      "baseAtk": "431",
      "baseDef": "866",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "freminet": {
    "Lv90": {
      "baseHp": "12071",
      "baseAtk": "255",
      "baseDef": "708",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "12906",
      "baseAtk": "320",
      "baseDef": "757",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "furina": {
    "Lv90": {
      "baseHp": "15307",
      "baseAtk": "244",
      "baseDef": "696",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "16395",
      "baseAtk": "299",
      "baseDef": "745",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "gaming": {
    "Lv90": {
      "baseHp": "11419",
      "baseAtk": "302",
      "baseDef": "703",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "12208",
      "baseAtk": "379",
      "baseDef": "752",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "ganyu": {
    "Lv90": {
      "baseHp": "9797",
      "baseAtk": "335",
      "baseDef": "630",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "10493",
      "baseAtk": "410",
      "baseDef": "675",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "gorou": {
    "Lv90": {
      "baseHp": "9570",
      "baseAtk": "183",
      "baseDef": "648",
      "em": "0",
      "geo%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10232",
      "baseAtk": "229",
      "baseDef": "693",
      "em": "0",
      "geo%": "24.0%"
    }
  },
  "hu_tao": {
    "Lv90": {
      "baseHp": "15552",
      "baseAtk": "106",
      "baseDef": "876",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "16658",
      "baseAtk": "130",
      "baseDef": "938",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "iansan": {
    "Lv90": {
      "baseHp": "10657",
      "baseAtk": "257",
      "baseDef": "638",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11395",
      "baseAtk": "323",
      "baseDef": "682",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "ifa": {
    "Lv90": {
      "baseHp": "10081",
      "baseAtk": "178",
      "baseDef": "605",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "10778",
      "baseAtk": "224",
      "baseDef": "647",
      "em": "96"
    }
  },
  "illuga": {
    "Lv90": {
      "baseHp": "11962",
      "baseAtk": "191",
      "baseDef": "814",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "12790",
      "baseAtk": "240",
      "baseDef": "870",
      "em": "96"
    }
  },
  "ineffa": {
    "Lv90": {
      "baseHp": "12613",
      "baseAtk": "330",
      "baseDef": "828",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "13510",
      "baseAtk": "404",
      "baseDef": "887",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "jahoda": {
    "Lv90": {
      "baseHp": "9646",
      "baseAtk": "223",
      "baseDef": "580",
      "em": "0",
      "heal%": "18.5%"
    },
    "Lv100": {
      "baseHp": "10313",
      "baseAtk": "280",
      "baseDef": "620",
      "em": "0",
      "heal%": "18.5%"
    }
  },
  "jean": {
    "Lv90": {
      "baseHp": "14695",
      "baseAtk": "239",
      "baseDef": "769",
      "em": "0",
      "heal%": "22.1%"
    },
    "Lv100": {
      "baseHp": "15740",
      "baseAtk": "293",
      "baseDef": "823",
      "em": "0",
      "heal%": "22.1%"
    }
  },
  "kachina": {
    "Lv90": {
      "baseHp": "11799",
      "baseAtk": "217",
      "baseDef": "792",
      "em": "0",
      "geo%": "24.0%"
    },
    "Lv100": {
      "baseHp": "12615",
      "baseAtk": "272",
      "baseDef": "847",
      "em": "0",
      "geo%": "24.0%"
    }
  },
  "kaedehara_kazuha": {
    "Lv90": {
      "baseHp": "13348",
      "baseAtk": "297",
      "baseDef": "807",
      "em": "115"
    },
    "Lv100": {
      "baseHp": "14297",
      "baseAtk": "363",
      "baseDef": "864",
      "em": "115"
    }
  },
  "kaeya": {
    "Lv90": {
      "baseHp": "11636",
      "baseAtk": "223",
      "baseDef": "792",
      "em": "0",
      "er": "26.7%"
    },
    "Lv100": {
      "baseHp": "12441",
      "baseAtk": "280",
      "baseDef": "846",
      "em": "0",
      "er": "26.7%"
    }
  },
  "kamisato_ayaka": {
    "Lv90": {
      "baseHp": "12858",
      "baseAtk": "342",
      "baseDef": "784",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13772",
      "baseAtk": "419",
      "baseDef": "840",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "kamisato_ayato": {
    "Lv90": {
      "baseHp": "13715",
      "baseAtk": "299",
      "baseDef": "769",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "14690",
      "baseAtk": "366",
      "baseDef": "823",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "kaveh": {
    "Lv90": {
      "baseHp": "11962",
      "baseAtk": "234",
      "baseDef": "751",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "12790",
      "baseAtk": "293",
      "baseDef": "803",
      "em": "96"
    }
  },
  "keqing": {
    "Lv90": {
      "baseHp": "13103",
      "baseAtk": "323",
      "baseDef": "799",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "14034",
      "baseAtk": "396",
      "baseDef": "856",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "kinich": {
    "Lv90": {
      "baseHp": "12858",
      "baseAtk": "332",
      "baseDef": "802",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13772",
      "baseAtk": "407",
      "baseDef": "859",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "kirara": {
    "Lv90": {
      "baseHp": "12180",
      "baseAtk": "223",
      "baseDef": "546",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13022",
      "baseAtk": "280",
      "baseDef": "584",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "klee": {
    "Lv90": {
      "baseHp": "10287",
      "baseAtk": "311",
      "baseDef": "615",
      "em": "0",
      "pyro%": "28.8%"
    },
    "Lv100": {
      "baseHp": "11018",
      "baseAtk": "381",
      "baseDef": "659",
      "em": "0",
      "pyro%": "28.8%"
    }
  },
  "kujou_sara": {
    "Lv90": {
      "baseHp": "9570",
      "baseAtk": "195",
      "baseDef": "628",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10232",
      "baseAtk": "245",
      "baseDef": "671",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "kuki_shinobu": {
    "Lv90": {
      "baseHp": "12289",
      "baseAtk": "212",
      "baseDef": "751",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13139",
      "baseAtk": "267",
      "baseDef": "803",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "lan_yan": {
    "Lv90": {
      "baseHp": "9244",
      "baseAtk": "251",
      "baseDef": "580",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "9883",
      "baseAtk": "315",
      "baseDef": "620",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "lauma": {
    "Lv90": {
      "baseHp": "10654",
      "baseAtk": "255",
      "baseDef": "669",
      "em": "315"
    },
    "Lv100": {
      "baseHp": "11411",
      "baseAtk": "312",
      "baseDef": "716",
      "em": "315"
    }
  },
  "layla": {
    "Lv90": {
      "baseHp": "11092",
      "baseAtk": "217",
      "baseDef": "655",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11860",
      "baseAtk": "272",
      "baseDef": "701",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "lisa": {
    "Lv90": {
      "baseHp": "9570",
      "baseAtk": "232",
      "baseDef": "573",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "10232",
      "baseAtk": "291",
      "baseDef": "613",
      "em": "96"
    }
  },
  "lynette": {
    "Lv90": {
      "baseHp": "12397",
      "baseAtk": "232",
      "baseDef": "712",
      "em": "0",
      "anemo%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13255",
      "baseAtk": "291",
      "baseDef": "761",
      "em": "0",
      "anemo%": "24.0%"
    }
  },
  "lyney": {
    "Lv90": {
      "baseHp": "11021",
      "baseAtk": "318",
      "baseDef": "538",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "11805",
      "baseAtk": "390",
      "baseDef": "576",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "mavuika": {
    "Lv90": {
      "baseHp": "12552",
      "baseAtk": "359",
      "baseDef": "792",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13444",
      "baseAtk": "439",
      "baseDef": "848",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "mika": {
    "Lv90": {
      "baseHp": "12506",
      "baseAtk": "223",
      "baseDef": "713",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13371",
      "baseAtk": "280",
      "baseDef": "763",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "mona": {
    "Lv90": {
      "baseHp": "10409",
      "baseAtk": "287",
      "baseDef": "653",
      "em": "0",
      "er": "32.0%"
    },
    "Lv100": {
      "baseHp": "11149",
      "baseAtk": "352",
      "baseDef": "700",
      "em": "0",
      "er": "32.0%"
    }
  },
  "mualani": {
    "Lv90": {
      "baseHp": "15185",
      "baseAtk": "182",
      "baseDef": "570",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "16264",
      "baseAtk": "223",
      "baseDef": "611",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "nahida": {
    "Lv90": {
      "baseHp": "10360",
      "baseAtk": "299",
      "baseDef": "630",
      "em": "115"
    },
    "Lv100": {
      "baseHp": "11096",
      "baseAtk": "366",
      "baseDef": "675",
      "em": "115"
    }
  },
  "navia": {
    "Lv90": {
      "baseHp": "12650",
      "baseAtk": "352",
      "baseDef": "793",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13549",
      "baseAtk": "431",
      "baseDef": "850",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "nefer": {
    "Lv90": {
      "baseHp": "12704",
      "baseAtk": "344",
      "baseDef": "799",
      "em": "100",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13607",
      "baseAtk": "422",
      "baseDef": "856",
      "em": "100",
      "cd": "38.4%"
    }
  },
  "neuvillette": {
    "Lv90": {
      "baseHp": "14695",
      "baseAtk": "208",
      "baseDef": "576",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "15740",
      "baseAtk": "255",
      "baseDef": "617",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "nilou": {
    "Lv90": {
      "baseHp": "15185",
      "baseAtk": "230",
      "baseDef": "729",
      "em": "0",
      "hp%": "28.8%"
    },
    "Lv100": {
      "baseHp": "16264",
      "baseAtk": "281",
      "baseDef": "780",
      "em": "0",
      "hp%": "28.8%"
    }
  },
  "ningguang": {
    "Lv90": {
      "baseHp": "9787",
      "baseAtk": "212",
      "baseDef": "573",
      "em": "0",
      "geo%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10464",
      "baseAtk": "267",
      "baseDef": "613",
      "em": "0",
      "geo%": "24.0%"
    }
  },
  "noelle": {
    "Lv90": {
      "baseHp": "12071",
      "baseAtk": "191",
      "baseDef": "799",
      "em": "0",
      "def%": "30.0%"
    },
    "Lv100": {
      "baseHp": "12906",
      "baseAtk": "240",
      "baseDef": "854",
      "em": "0",
      "def%": "30.0%"
    }
  },
  "ororon": {
    "Lv90": {
      "baseHp": "9244",
      "baseAtk": "244",
      "baseDef": "587",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "9883",
      "baseAtk": "307",
      "baseDef": "628",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "qiqi": {
    "Lv90": {
      "baseHp": "12368",
      "baseAtk": "287",
      "baseDef": "922",
      "em": "0",
      "heal%": "22.1%"
    },
    "Lv100": {
      "baseHp": "13247",
      "baseAtk": "352",
      "baseDef": "988",
      "em": "0",
      "heal%": "22.1%"
    }
  },
  "raiden_shogun": {
    "Lv90": {
      "baseHp": "12907",
      "baseAtk": "337",
      "baseDef": "789",
      "em": "0",
      "er": "32.0%"
    },
    "Lv100": {
      "baseHp": "13825",
      "baseAtk": "413",
      "baseDef": "845",
      "em": "0",
      "er": "32.0%"
    }
  },
  "razor": {
    "Lv90": {
      "baseHp": "11962",
      "baseAtk": "234",
      "baseDef": "751",
      "em": "0",
      "phys%": "30.0%"
    },
    "Lv100": {
      "baseHp": "12790",
      "baseAtk": "293",
      "baseDef": "803",
      "em": "0",
      "phys%": "30.0%"
    }
  },
  "rosaria": {
    "Lv90": {
      "baseHp": "12289",
      "baseAtk": "240",
      "baseDef": "710",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13139",
      "baseAtk": "301",
      "baseDef": "759",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "sangonomiya_kokomi": {
    "Lv90": {
      "baseHp": "13471",
      "baseAtk": "234",
      "baseDef": "657",
      "em": "0",
      "hydro%": "28.8%"
    },
    "Lv100": {
      "baseHp": "14428",
      "baseAtk": "287",
      "baseDef": "704",
      "em": "0",
      "hydro%": "28.8%"
    }
  },
  "sayu": {
    "Lv90": {
      "baseHp": "11854",
      "baseAtk": "244",
      "baseDef": "745",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "12674",
      "baseAtk": "307",
      "baseDef": "796",
      "em": "96"
    }
  },
  "sethos": {
    "Lv90": {
      "baseHp": "9787",
      "baseAtk": "227",
      "baseDef": "560",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "10464",
      "baseAtk": "285",
      "baseDef": "598",
      "em": "96"
    }
  },
  "shenhe": {
    "Lv90": {
      "baseHp": "12993",
      "baseAtk": "304",
      "baseDef": "830",
      "em": "0",
      "atk%": "28.8%"
    },
    "Lv100": {
      "baseHp": "13916",
      "baseAtk": "372",
      "baseDef": "889",
      "em": "0",
      "atk%": "28.8%"
    }
  },
  "shikanoin_heizou": {
    "Lv90": {
      "baseHp": "10657",
      "baseAtk": "225",
      "baseDef": "684",
      "em": "0",
      "anemo%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11395",
      "baseAtk": "283",
      "baseDef": "731",
      "em": "0",
      "anemo%": "24.0%"
    }
  },
  "sigewinne": {
    "Lv90": {
      "baseHp": "13348",
      "baseAtk": "193",
      "baseDef": "500",
      "em": "0",
      "hp%": "28.8%"
    },
    "Lv100": {
      "baseHp": "14297",
      "baseAtk": "236",
      "baseDef": "535",
      "em": "0",
      "hp%": "28.8%"
    }
  },
  "skirk": {
    "Lv90": {
      "baseHp": "12417",
      "baseAtk": "359",
      "baseDef": "806",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13300",
      "baseAtk": "439",
      "baseDef": "864",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "sucrose": {
    "Lv90": {
      "baseHp": "9244",
      "baseAtk": "170",
      "baseDef": "703",
      "em": "0",
      "anemo%": "24.0%"
    },
    "Lv100": {
      "baseHp": "9883",
      "baseAtk": "213",
      "baseDef": "752",
      "em": "0",
      "anemo%": "24.0%"
    }
  },
  "tartaglia": {
    "Lv90": {
      "baseHp": "13103",
      "baseAtk": "301",
      "baseDef": "815",
      "em": "0",
      "hydro%": "28.8%"
    },
    "Lv100": {
      "baseHp": "14034",
      "baseAtk": "369",
      "baseDef": "873",
      "em": "0",
      "hydro%": "28.8%"
    }
  },
  "thoma": {
    "Lv90": {
      "baseHp": "10331",
      "baseAtk": "202",
      "baseDef": "751",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11046",
      "baseAtk": "253",
      "baseDef": "803",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "tighnari": {
    "Lv90": {
      "baseHp": "10850",
      "baseAtk": "268",
      "baseDef": "630",
      "em": "0",
      "dendro%": "28.8%"
    },
    "Lv100": {
      "baseHp": "11621",
      "baseAtk": "328",
      "baseDef": "675",
      "em": "0",
      "dendro%": "28.8%"
    }
  },
  "varesa": {
    "Lv90": {
      "baseHp": "12699",
      "baseAtk": "356",
      "baseDef": "782",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "13602",
      "baseAtk": "437",
      "baseDef": "837",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "varka": {
    "Lv90": {
      "baseHp": "12613",
      "baseAtk": "353",
      "baseDef": "795",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13510",
      "baseAtk": "432",
      "baseDef": "852",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "venti": {
    "Lv90": {
      "baseHp": "10531",
      "baseAtk": "263",
      "baseDef": "669",
      "em": "0",
      "er": "32.0%"
    },
    "Lv100": {
      "baseHp": "11280",
      "baseAtk": "322",
      "baseDef": "716",
      "em": "0",
      "er": "32.0%"
    }
  },
  "wanderer": {
    "Lv90": {
      "baseHp": "10164",
      "baseAtk": "328",
      "baseDef": "607",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "10887",
      "baseAtk": "401",
      "baseDef": "650",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "wriothesley": {
    "Lv90": {
      "baseHp": "13593",
      "baseAtk": "311",
      "baseDef": "763",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "14559",
      "baseAtk": "381",
      "baseDef": "817",
      "em": "0",
      "cd": "38.4%"
    }
  },
  "xiangling": {
    "Lv90": {
      "baseHp": "10875",
      "baseAtk": "225",
      "baseDef": "669",
      "em": "96"
    },
    "Lv100": {
      "baseHp": "11627",
      "baseAtk": "283",
      "baseDef": "715",
      "em": "96"
    }
  },
  "xianyun": {
    "Lv90": {
      "baseHp": "10409",
      "baseAtk": "335",
      "baseDef": "573",
      "em": "0",
      "atk%": "28.8%"
    },
    "Lv100": {
      "baseHp": "11149",
      "baseAtk": "410",
      "baseDef": "613",
      "em": "0",
      "atk%": "28.8%"
    }
  },
  "xiao": {
    "Lv90": {
      "baseHp": "12736",
      "baseAtk": "349",
      "baseDef": "799",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "13641",
      "baseAtk": "428",
      "baseDef": "856",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "xilonen": {
    "Lv90": {
      "baseHp": "12405",
      "baseAtk": "275",
      "baseDef": "930",
      "em": "0",
      "def%": "36.0%"
    },
    "Lv100": {
      "baseHp": "13287",
      "baseAtk": "337",
      "baseDef": "996",
      "em": "0",
      "def%": "36.0%"
    }
  },
  "xingqiu": {
    "Lv90": {
      "baseHp": "10222",
      "baseAtk": "202",
      "baseDef": "758",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "10930",
      "baseAtk": "253",
      "baseDef": "810",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "xinyan": {
    "Lv90": {
      "baseHp": "11201",
      "baseAtk": "249",
      "baseDef": "799",
      "em": "0",
      "atk%": "24.0%"
    },
    "Lv100": {
      "baseHp": "11976",
      "baseAtk": "312",
      "baseDef": "854",
      "em": "0",
      "atk%": "24.0%"
    }
  },
  "yae_miko": {
    "Lv90": {
      "baseHp": "10372",
      "baseAtk": "340",
      "baseDef": "569",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "11109",
      "baseAtk": "416",
      "baseDef": "609",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "yanfei": {
    "Lv90": {
      "baseHp": "9352",
      "baseAtk": "240",
      "baseDef": "587",
      "em": "0",
      "pyro%": "24.0%"
    },
    "Lv100": {
      "baseHp": "9999",
      "baseAtk": "301",
      "baseDef": "628",
      "em": "0",
      "pyro%": "24.0%"
    }
  },
  "yaoyao": {
    "Lv90": {
      "baseHp": "12289",
      "baseAtk": "212",
      "baseDef": "751",
      "em": "0",
      "hp%": "24.0%"
    },
    "Lv100": {
      "baseHp": "13139",
      "baseAtk": "267",
      "baseDef": "803",
      "em": "0",
      "hp%": "24.0%"
    }
  },
  "yelan": {
    "Lv90": {
      "baseHp": "14450",
      "baseAtk": "244",
      "baseDef": "548",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "15477",
      "baseAtk": "299",
      "baseDef": "587",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "yoimiya": {
    "Lv90": {
      "baseHp": "10164",
      "baseAtk": "323",
      "baseDef": "615",
      "em": "0",
      "cr": "19.2%"
    },
    "Lv100": {
      "baseHp": "10887",
      "baseAtk": "396",
      "baseDef": "659",
      "em": "0",
      "cr": "19.2%"
    }
  },
  "yumemizuki_mizuki": {
    "Lv90": {
      "baseHp": "12736",
      "baseAtk": "215",
      "baseDef": "757",
      "em": "115"
    },
    "Lv100": {
      "baseHp": "13641",
      "baseAtk": "264",
      "baseDef": "811",
      "em": "115"
    }
  },
  "yun_jin": {
    "Lv90": {
      "baseHp": "10657",
      "baseAtk": "191",
      "baseDef": "734",
      "em": "0",
      "er": "26.7%"
    },
    "Lv100": {
      "baseHp": "11395",
      "baseAtk": "240",
      "baseDef": "785",
      "em": "0",
      "er": "26.7%"
    }
  },
  "zhongli": {
    "Lv90": {
      "baseHp": "14695",
      "baseAtk": "251",
      "baseDef": "738",
      "em": "0",
      "geo%": "28.8%"
    },
    "Lv100": {
      "baseHp": "15740",
      "baseAtk": "308",
      "baseDef": "790",
      "em": "0",
      "geo%": "28.8%"
    }
  },
  "zibai": {
    "Lv90": {
      "baseHp": "12919",
      "baseAtk": "225",
      "baseDef": "957",
      "em": "0",
      "cd": "38.4%"
    },
    "Lv100": {
      "baseHp": "13838",
      "baseAtk": "275",
      "baseDef": "1025",
      "em": "0",
      "cd": "38.4%"
    }
  }
};
