// This file is auto-generated by scripts/lunaris.py
// Do not edit this file directly

export const i18nBetaData = {
  characters: {
    "lohen": { en: "Lohen", zh: "洛恩" },
  },
  weapons: {
    "disaster_and_remorse": { en: "Disaster and Remorse", zh: "灾悔" },
  },
  artifacts: {
    "glacier_and_snowfield": { en: "Glacier and Snowfield", zh: "冰之川与雪之砂" },
  },
};
