// This file is auto-generated by scripts/lunaris.py
// Do not edit this file directly

export const i18nBetaData = {
  characters: {
  },
  weapons: {
    "prized_isshin_blade": { en: "Prized Isshin Blade", zh: "「一心传」名刀" },
  },
  artifacts: {
    "glacier_and_snowfield": { en: "Glacier and Snowfield", zh: "冰之川与雪之砂" },
  },
};
