// This file is auto-generated by scripts/codedump.py
// Do not edit this file directly

export const i18nGameData = {
  "characters": {
    "jahoda": {
      "en": "Jahoda",
      "zh": "雅珂达"
    },
    "durin": {
      "en": "Durin",
      "zh": "杜林"
    },
    "nefer": {
      "en": "Nefer",
      "zh": "奈芙尔"
    },
    "flins": {
      "en": "Flins",
      "zh": "菲林斯"
    },
    "aino": {
      "en": "Aino",
      "zh": "爱诺"
    },
    "lauma": {
      "en": "Lauma",
      "zh": "菈乌玛"
    },
    "ineffa": {
      "en": "Ineffa",
      "zh": "伊涅芙"
    },
    "dahlia": {
      "en": "Dahlia",
      "zh": "塔利雅"
    },
    "skirk": {
      "en": "Skirk",
      "zh": "丝柯克"
    },
    "ifa": {
      "en": "Ifa",
      "zh": "伊法"
    },
    "escoffier": {
      "en": "Escoffier",
      "zh": "爱可菲"
    },
    "iansan": {
      "en": "Iansan",
      "zh": "伊安珊"
    },
    "varesa": {
      "en": "Varesa",
      "zh": "瓦雷莎"
    },
    "yumemizuki_mizuki": {
      "en": "Yumemizuki Mizuki",
      "zh": "梦见月瑞希"
    },
    "traveler_pyro": {
      "en": "Traveler (Pyro)",
      "zh": "旅行者（火）"
    },
    "lan_yan": {
      "en": "Lan Yan",
      "zh": "蓝砚"
    },
    "citlali": {
      "en": "Citlali",
      "zh": "茜特菈莉"
    },
    "mavuika": {
      "en": "Mavuika",
      "zh": "玛薇卡"
    },
    "chasca": {
      "en": "Chasca",
      "zh": "恰斯卡"
    },
    "ororon": {
      "en": "Ororon",
      "zh": "欧洛伦"
    },
    "xilonen": {
      "en": "Xilonen",
      "zh": "希诺宁"
    },
    "mualani": {
      "en": "Mualani",
      "zh": "玛拉妮"
    },
    "kachina": {
      "en": "Kachina",
      "zh": "卡齐娜"
    },
    "kinich": {
      "en": "Kinich",
      "zh": "基尼奇"
    },
    "emilie": {
      "en": "Emilie",
      "zh": "艾梅莉埃"
    },
    "sethos": {
      "en": "Sethos",
      "zh": "赛索斯"
    },
    "sigewinne": {
      "en": "Sigewinne",
      "zh": "希格雯"
    },
    "clorinde": {
      "en": "Clorinde",
      "zh": "克洛琳德"
    },
    "arlecchino": {
      "en": "Arlecchino",
      "zh": "阿蕾奇诺"
    },
    "chiori": {
      "en": "Chiori",
      "zh": "千织"
    },
    "gaming": {
      "en": "Gaming",
      "zh": "嘉明"
    },
    "xianyun": {
      "en": "Xianyun",
      "zh": "闲云"
    },
    "chevreuse": {
      "en": "Chevreuse",
      "zh": "夏沃蕾"
    },
    "navia": {
      "en": "Navia",
      "zh": "娜维娅"
    },
    "charlotte": {
      "en": "Charlotte",
      "zh": "夏洛蒂"
    },
    "furina": {
      "en": "Furina",
      "zh": "芙宁娜"
    },
    "neuvillette": {
      "en": "Neuvillette",
      "zh": "那维莱特"
    },
    "wriothesley": {
      "en": "Wriothesley",
      "zh": "莱欧斯利"
    },
    "traveler_hydro": {
      "en": "Traveler (Hydro)",
      "zh": "旅行者（水）"
    },
    "freminet": {
      "en": "Freminet",
      "zh": "菲米尼"
    },
    "lyney": {
      "en": "Lyney",
      "zh": "林尼"
    },
    "lynette": {
      "en": "Lynette",
      "zh": "琳妮特"
    },
    "kirara": {
      "en": "Kirara",
      "zh": "绮良良"
    },
    "baizhu": {
      "en": "Baizhu",
      "zh": "白术"
    },
    "kaveh": {
      "en": "Kaveh",
      "zh": "卡维"
    },
    "dehya": {
      "en": "Dehya",
      "zh": "迪希雅"
    },
    "mika": {
      "en": "Mika",
      "zh": "米卡"
    },
    "alhaitham": {
      "en": "Alhaitham",
      "zh": "艾尔海森"
    },
    "yaoyao": {
      "en": "Yaoyao",
      "zh": "瑶瑶"
    },
    "wanderer": {
      "en": "Wanderer",
      "zh": "流浪者"
    },
    "faruzan": {
      "en": "Faruzan",
      "zh": "珐露珊"
    },
    "layla": {
      "en": "Layla",
      "zh": "莱依拉"
    },
    "nahida": {
      "en": "Nahida",
      "zh": "纳西妲"
    },
    "candace": {
      "en": "Candace",
      "zh": "坎蒂丝"
    },
    "cyno": {
      "en": "Cyno",
      "zh": "赛诺"
    },
    "nilou": {
      "en": "Nilou",
      "zh": "妮露"
    },
    "traveler_dendro": {
      "en": "Traveler (Dendro)",
      "zh": "旅行者（草）"
    },
    "dori": {
      "en": "Dori",
      "zh": "多莉"
    },
    "collei": {
      "en": "Collei",
      "zh": "柯莱"
    },
    "tighnari": {
      "en": "Tighnari",
      "zh": "提纳里"
    },
    "shikanoin_heizou": {
      "en": "Shikanoin Heizou",
      "zh": "鹿野院平藏"
    },
    "kuki_shinobu": {
      "en": "Kuki Shinobu",
      "zh": "久岐忍"
    },
    "yelan": {
      "en": "Yelan",
      "zh": "夜兰"
    },
    "xiao": {
      "en": "Xiao",
      "zh": "魈"
    },
    "xiangling": {
      "en": "Xiangling",
      "zh": "香菱"
    },
    "raiden_shogun": {
      "en": "Raiden Shogun",
      "zh": "雷电将军"
    },
    "razor": {
      "en": "Razor",
      "zh": "雷泽"
    },
    "albedo": {
      "en": "Albedo",
      "zh": "阿贝多"
    },
    "zhongli": {
      "en": "Zhongli",
      "zh": "钟离"
    },
    "chongyun": {
      "en": "Chongyun",
      "zh": "重云"
    },
    "diona": {
      "en": "Diona",
      "zh": "迪奥娜"
    },
    "diluc": {
      "en": "Diluc",
      "zh": "迪卢克"
    },
    "tartaglia": {
      "en": "Tartaglia",
      "zh": "达达利亚"
    },
    "xinyan": {
      "en": "Xinyan",
      "zh": "辛焱"
    },
    "noelle": {
      "en": "Noelle",
      "zh": "诺艾尔"
    },
    "xingqiu": {
      "en": "Xingqiu",
      "zh": "行秋"
    },
    "fischl": {
      "en": "Fischl",
      "zh": "菲谢尔"
    },
    "mona": {
      "en": "Mona",
      "zh": "莫娜"
    },
    "arataki_itto": {
      "en": "Arataki Itto",
      "zh": "荒泷一斗"
    },
    "barbara": {
      "en": "Barbara",
      "zh": "芭芭拉"
    },
    "hu_tao": {
      "en": "Hu Tao",
      "zh": "胡桃"
    },
    "rosaria": {
      "en": "Rosaria",
      "zh": "罗莎莉亚"
    },
    "kamisato_ayaka": {
      "en": "Kamisato Ayaka",
      "zh": "神里绫华"
    },
    "kamisato_ayato": {
      "en": "Kamisato Ayato",
      "zh": "神里绫人"
    },
    "sucrose": {
      "en": "Sucrose",
      "zh": "砂糖"
    },
    "shenhe": {
      "en": "Shenhe",
      "zh": "申鹤"
    },
    "ganyu": {
      "en": "Ganyu",
      "zh": "甘雨"
    },
    "jean": {
      "en": "Jean",
      "zh": "琴"
    },
    "bennett": {
      "en": "Bennett",
      "zh": "班尼特"
    },
    "sangonomiya_kokomi": {
      "en": "Sangonomiya Kokomi",
      "zh": "珊瑚宫心海"
    },
    "yanfei": {
      "en": "Yanfei",
      "zh": "烟绯"
    },
    "venti": {
      "en": "Venti",
      "zh": "温迪"
    },
    "kaedehara_kazuha": {
      "en": "Kaedehara Kazuha",
      "zh": "枫原万叶"
    },
    "sayu": {
      "en": "Sayu",
      "zh": "早柚"
    },
    "traveler_anemo": {
      "en": "Traveler (Anemo)",
      "zh": "旅行者（风）"
    },
    "traveler_electro": {
      "en": "Traveler (Electro)",
      "zh": "旅行者（雷）"
    },
    "traveler_geo": {
      "en": "Traveler (Geo)",
      "zh": "旅行者（岩）"
    },
    "thoma": {
      "en": "Thoma",
      "zh": "托马"
    },
    "yoimiya": {
      "en": "Yoimiya",
      "zh": "宵宫"
    },
    "amber": {
      "en": "Amber",
      "zh": "安柏"
    },
    "aloy": {
      "en": "Aloy",
      "zh": "埃洛伊"
    },
    "klee": {
      "en": "Klee",
      "zh": "可莉"
    },
    "beidou": {
      "en": "Beidou",
      "zh": "北斗"
    },
    "keqing": {
      "en": "Keqing",
      "zh": "刻晴"
    },
    "kaeya": {
      "en": "Kaeya",
      "zh": "凯亚"
    },
    "ningguang": {
      "en": "Ningguang",
      "zh": "凝光"
    },
    "yae_miko": {
      "en": "Yae Miko",
      "zh": "八重神子"
    },
    "eula": {
      "en": "Eula",
      "zh": "优菈"
    },
    "gorou": {
      "en": "Gorou",
      "zh": "五郎"
    },
    "yun_jin": {
      "en": "Yun Jin",
      "zh": "云堇"
    },
    "kujou_sara": {
      "en": "Kujou Sara",
      "zh": "九条裟罗"
    },
    "lisa": {
      "en": "Lisa",
      "zh": "丽莎"
    },
    "qiqi": {
      "en": "Qiqi",
      "zh": "七七"
    }
  },
  "artifacts": {
    "silken_moons_serenade": {
      "name": {
        "en": "Silken Moon's Serenade",
        "zh": "纺月的夜歌"
      },
      "effects": {
        "en": [
          "Energy Recharge +20%.",
          "When dealing Elemental DMG, gain the Gleaming Moon: Devotion effect for 8s: Increases all party members' Elemental Mastery by 60/120 when the party's Moonsign is Nascent Gleam/Ascendant Gleam. The equipping character can trigger this effect while off-field. All party members' Lunar Reaction DMG is increased by 10% for each different Gleaming Moon effect that party members have. Effects from Gleaming Moon cannot stack."
        ],
        "zh": [
          "元素充能效率提高20%。",
          "造成元素伤害时，获得持续8秒的「月辉明光·崇信」效果：队伍的月兆为初辉/满辉时，队伍中的所有角色的元素精通提高60点/120点。装备者处于后台时也能触发上述效果。队伍中的角色每拥有一种不同的「月辉明光」效果，队伍中的所有角色触发的月曜反应造成的伤害提升10%。由「月辉明光」产生的效果无法叠加。"
        ]
      }
    },
    "night_of_the_skys_unveiling": {
      "name": {
        "en": "Night of the Sky's Unveiling",
        "zh": "穹境示现之夜"
      },
      "effects": {
        "en": [
          "Increases Elemental Mastery by 80.",
          "When nearby party members trigger Lunar Reactions, if the equipping character is on the field, gain the Gleaming Moon: Intent effect for 4s: Increases CRIT Rate by 15%/30% when the party's Moonsign is Nascent Gleam/Ascendant Gleam. All party members' Lunar Reaction DMG is increased by 10% for each different Gleaming Moon effect that party members have. Effects from Gleaming Moon cannot stack."
        ],
        "zh": [
          "元素精通提高80点。",
          "队伍中附近的角色触发月曜反应时，若装备者在场上，将获得持续4秒的「月辉明光·蓄念」效果：队伍的月兆为初辉/满辉时，暴击率提升15%/30%。队伍中的角色每拥有一种不同的「月辉明光」效果，队伍中的所有角色触发的月曜反应造成的伤害提升10%。由「月辉明光」产生的效果无法叠加。"
        ]
      }
    },
    "finale_of_the_deep_galleries": {
      "name": {
        "en": "Finale of the Deep Galleries",
        "zh": "深廊终曲"
      },
      "effects": {
        "en": [
          "Cryo DMG Bonus +15%",
          "When the equipping character has 0 Elemental Energy, Normal Attack DMG is increased by 60% and Elemental Burst DMG is increased by 60%. After the equipping character deals Normal Attack DMG, the aforementioned Elemental Burst effect will stop applying for 6s. After the equipping character deals Elemental Burst DMG, the aforementioned Normal Attack effect will stop applying for 6s. This effect can trigger even if the equipping character is off the field."
        ],
        "zh": [
          "获得15%冰元素伤害加成。",
          "装备者的元素能量为0时，普通攻击造成的伤害提升60%，元素爆发造成的伤害提升60%。装备者的普通攻击造成伤害后，上述元素爆发伤害提升效果将失效6秒；装备者的元素爆发造成伤害后，上述普通攻击伤害提升效果将失效6秒。角色处于队伍后台也能触发。"
        ]
      }
    },
    "long_nights_oath": {
      "name": {
        "en": "Long Night's Oath",
        "zh": "长夜之誓"
      },
      "effects": {
        "en": [
          "Plunging Attack DMG increased by 25%.",
          "After the equipping character's Plunging Attack/Charged Attack/Elemental Skill hits an opponent, they will gain 1/2/2 stack(s) of \"Radiance Everlasting.\" Plunging Attacks, Charged Attacks, or Elemental Skills can each trigger this effect once every 1s. Radiance Everlasting: Plunging Attacks deal 15% increased DMG for 6s. Max 5 stacks. Each stack's duration is counted independently."
        ],
        "zh": [
          "下落攻击造成的伤害提升25%。",
          "装备者的下落攻击/重击/元素战技命中敌人后，获得1/2/2层「永照的流辉」，由下落攻击、重击或元素战技产生的该效果分别每1秒至多触发一次。永照的流辉：下落攻击造成的伤害提升15%，持续6秒，至多叠加5层，每层持续时间独立计算。"
        ]
      }
    },
    "obsidian_codex": {
      "name": {
        "en": "Obsidian Codex",
        "zh": "黑曜秘典"
      },
      "effects": {
        "en": [
          "While the equipping character is in Nightsoul's Blessing and is on the field, their DMG dealt is increased by 15%.",
          "After the equipping character consumes 1 Nightsoul point while on the field, CRIT Rate increases by 40% for 6s. This effect can trigger once every second."
        ],
        "zh": [
          "装备者处于夜魂加持状态，并且在场上时，造成的伤害提高15%。",
          "装备者在场上消耗1点夜魂值后，暴击率提高40%，持续6秒。该效果每1秒至多触发一次。"
        ]
      }
    },
    "scroll_of_the_hero_of_cinder_city": {
      "name": {
        "en": "Scroll of the Hero of Cinder City",
        "zh": "烬城勇者绘卷"
      },
      "effects": {
        "en": [
          "When a nearby party member triggers a Nightsoul Burst, the equipping character regenerates 6 Energy.",
          "After the equipping character triggers a reaction related to their Elemental Type, all nearby party members gain a 12% Elemental DMG Bonus for reaction-proximate Elemental Types for 15s. If the equipping character is in the Nightsoul's Blessing state when triggering this effect, all nearby party members gain an additional 28% Elemental DMG Bonus for reaction-proximate Elemental Types for 20s. The equipping character can trigger this effect while off-field, and the DMG bonus from Artifact Sets with the same name do not stack."
        ],
        "zh": [
          "队伍中附近的角色触发「夜魂迸发」时，装备者恢复6点元素能量。",
          "装备者触发其对应元素类型的相关反应后，队伍中附近的所有角色的该元素反应相关的元素伤害加成提升12%，持续15秒。若触发该效果时，装备者处于夜魂加持状态下，还将使队伍中附近的所有角色的与该元素反应相关的元素伤害加成提升28%，持续20秒。装备者处于后台时也能触发上述效果。同名圣遗物套装产生的伤害加成效果无法叠加。"
        ]
      }
    },
    "unfinished_reverie": {
      "name": {
        "en": "Unfinished Reverie",
        "zh": "未竟的遐思"
      },
      "effects": {
        "en": [
          "ATK +18%.",
          "After leaving combat for 3s, DMG dealt increased by 50%. In combat, if no Burning opponents are nearby for more than 6s, this DMG Bonus will decrease by 10% per second until it reaches 0%. When a Burning opponent exists, it will increase by 10% instead until it reaches 50%. This effect still triggers if the equipping character is off-field."
        ],
        "zh": [
          "攻击力提高18%。",
          "脱离战斗状态3秒后，造成的伤害提升50%。在战斗状态下，附近不存在处于燃烧状态下的敌人超过6秒后，上述伤害提升效果每秒降低10%，直到降低至0%；存在处于燃烧状态下的敌人时，每秒提升10%，直到达到50%。装备此圣遗物套装的角色处于队伍后台时，依然会触发该效果。"
        ]
      }
    },
    "fragment_of_harmonic_whimsy": {
      "name": {
        "en": "Fragment of Harmonic Whimsy",
        "zh": "谐律异想断章"
      },
      "effects": {
        "en": [
          "ATK +18%.",
          "When the value of a Bond of Life increases or decreases, this character deals 18% increased DMG for 6s. Max 3 stacks."
        ],
        "zh": [
          "攻击力提高18%。",
          "生命之契的数值提升或降低时，角色造成的伤害提升18%，该效果持续6秒，至多叠加3次。"
        ]
      }
    },
    "song_of_days_past": {
      "name": {
        "en": "Song of Days Past",
        "zh": "昔时之歌"
      },
      "effects": {
        "en": [
          "Healing Bonus +15%.",
          "When the equipping character heals a party member, the Yearning effect will be created for 6s, which records the total amount of healing provided (including overflow healing). When the duration expires, the Yearning effect will be transformed into the \"Waves of Days Past\" effect: When your active party member hits an opponent with a Normal Attack, Charged Attack, Plunging Attack, Elemental Skill, or Elemental Burst, the DMG dealt will be increased by 8% of the total healing amount recorded by the Yearning effect. The \"Waves of Days Past\" effect is removed after it has taken effect 5 times or after 10s. A single instance of the Yearning effect can record up to 15,000 healing, and only a single instance can exist at once, but it can record the healing from multiple equipping characters. Equipping characters on standby can still trigger this effect."
        ],
        "zh": [
          "治疗加成提高15%。",
          "装备者对队伍中的角色进行治疗时，将产生持续6秒的渴盼效果，记录治疗的生命值回复量（包括溢出值）。持续时间结束时，渴盼效果将转变为「彼时的浪潮」效果：队伍中自己的当前场上角色的普通攻击、重击、下落攻击、元素战技与元素爆发命中敌人时，将基于渴盼效果所记录的回复量的8%提高造成的伤害，「彼时的浪潮」将在生效5次或10秒后移除。一次渴盼效果至多记录15000点回复量，同时至多存在一个，能够记录多个装备者的产生的回复量；装备者处于队伍后台时，依然能触发该效果。"
        ]
      }
    },
    "nighttime_whispers_in_the_echoing_woods": {
      "name": {
        "en": "Nighttime Whispers in the Echoing Woods",
        "zh": "回声之林夜话"
      },
      "effects": {
        "en": [
          "ATK +18%.",
          "After using an Elemental Skill, gain a 20% Geo DMG Bonus for 10s. While under a shield granted by the Crystallize reaction, the above effect will be increased by 150%, and this additional increase disappears 1s after that shield is lost."
        ],
        "zh": [
          "攻击力提高18%。",
          "施放元素战技后的10秒内，岩元素伤害加成提升20%；若处于结晶反应产生的护盾庇护下，上述效果提高150%，进一步提高的效果将在失去结晶护盾庇护的1秒后移除。"
        ]
      }
    },
    "golden_troupe": {
      "name": {
        "en": "Golden Troupe",
        "zh": "黄金剧团"
      },
      "effects": {
        "en": [
          "Increases Elemental Skill DMG by 20%",
          "Increases Elemental Skill DMG by 25%. Additionally, when not on the field, Elemental Skill DMG will be further increased by 25%. This effect will be cleared 2s after taking the field."
        ],
        "zh": [
          "元素战技造成的伤害提升20%。",
          "元素战技造成的伤害提升25%；此外，处于队伍后台时，元素战技造成的伤害还将进一步提升25%，该效果将在登场2秒移除。"
        ]
      }
    },
    "marechaussee_hunter": {
      "name": {
        "en": "Marechaussee Hunter",
        "zh": "逐影猎人"
      },
      "effects": {
        "en": [
          "Normal and Charged Attack DMG +15%",
          "When current HP increases or decreases, CRIT Rate will be increased by 12% for 5s. Max 3 stacks."
        ],
        "zh": [
          "普通攻击与重击造成的伤害提高15%。",
          "当前生命值提升或降低时，暴击率提升12%，该效果持续5秒，至多叠加3次。"
        ]
      }
    },
    "vourukashas_glow": {
      "name": {
        "en": "Vourukasha's Glow",
        "zh": "花海甘露之光"
      },
      "effects": {
        "en": [
          "HP +20%",
          "Elemental Skill and Elemental Burst DMG will be increased by 10%. After the equipping character takes DMG, the aforementioned DMG Bonus is increased by 80% for 5s. This effect increase can have 5 stacks. The duration of each stack is counted independently. These effects can be triggered even when the equipping character is not on the field."
        ],
        "zh": [
          "生命值提升20%。",
          "元素战技与元素爆发造成的伤害提升10%；装备者受到伤害后的5秒内，上述伤害提升效果提高80%，该提高效果至多叠加5层，每层持续时间独立计算，处于队伍后台时依然能触发该效果。"
        ]
      }
    },
    "nymphs_dream": {
      "name": {
        "en": "Nymph's Dream",
        "zh": "水仙之梦"
      },
      "effects": {
        "en": [
          "Hydro DMG Bonus +15%",
          "After Normal, Charged, and Plunging Attacks, Elemental Skills, and Elemental Bursts hit opponents, 1 stack of Mirrored Nymph will be triggered, lasting 8s. When under the effect of 1, 2, or 3 or more Mirrored Nymph stacks, ATK will be increased by 7%/16%/25%, and Hydro DMG Bonus will be increased by 4%/9%/15%. Mirrored Nymph stacks created by Normal, Charged, and Plunging Attacks, Elemental Skills, and Elemental Bursts exist independently."
        ],
        "zh": [
          "获得15%水元素伤害加成。",
          "普通攻击、重击、下落攻击、元素战技或元素爆发命中敌人后，将产生1层持续8秒的「镜中水仙」效果。处于1/2/3层及以上「镜中水仙」效果下时，攻击力将提高7%/16%/25%，水元素伤害加成提升4%/9%/15%。由普通攻击、重击、下落攻击、元素战技或元素爆发产生的「镜中水仙」将分别独立存在。"
        ]
      }
    },
    "desert_pavilion_chronicle": {
      "name": {
        "en": "Desert Pavilion Chronicle",
        "zh": "沙上楼阁史话"
      },
      "effects": {
        "en": [
          "Anemo DMG Bonus +15%",
          "When Charged Attacks hit opponents, the equipping character's Normal Attack SPD will increase by 10% while Normal, Charged, and Plunging Attack DMG will increase by 40% for 15s."
        ],
        "zh": [
          "获得15%风元素伤害加成。",
          "重击命中敌人后，该角色的普通攻击速度提升10%，普通攻击、重击与下落攻击造成的伤害提升40%，持续15秒。"
        ]
      }
    },
    "flower_of_paradise_lost": {
      "name": {
        "en": "Flower of Paradise Lost",
        "zh": "乐园遗落之花"
      },
      "effects": {
        "en": [
          "Increases Elemental Mastery by 80.",
          "The equipping character's Bloom, Hyperbloom, and Burgeon reaction DMG are increased by 40%. Additionally, after the equipping character triggers Bloom, Hyperbloom, or Burgeon, they will gain another 25% bonus to the effect mentioned prior. Each stack of this lasts 10s. Max 4 stacks simultaneously. This effect can only be triggered once per second. The character who equips this can still trigger its effects when not on the field."
        ],
        "zh": [
          "元素精通提高80点。",
          "装备者绽放、超绽放、烈绽放反应造成的伤害提升40%。此外，装备者触发绽放、超绽放、烈绽放后，上述效果带来的加成提升25%，该效果持续10秒，至多叠加4次，每1秒至多触发一次。装备者处于队伍后台时依然能触发该效果。"
        ]
      }
    },
    "gilded_dreams": {
      "name": {
        "en": "Gilded Dreams",
        "zh": "饰金之梦"
      },
      "effects": {
        "en": [
          "Elemental Mastery +80.",
          "Within 8s of triggering an Elemental Reaction, the character equipping this will obtain buffs based on the Elemental Type of the other party members. ATK is increased by 14% for each party member whose Elemental Type is the same as the equipping character, and Elemental Mastery is increased by 50 for every party member with a different Elemental Type. Each of the aforementioned buffs will count up to 3 characters. This effect can be triggered once every 8s. The character who equips this can still trigger its effects when not on the field."
        ],
        "zh": [
          "元素精通提高80点",
          "触发元素反应后的8秒内，会根据队伍内其他角色的元素类型，使装备者获得强化：队伍中每存在1个和装备者同类元素角色，攻击力提升14%；每存在1个和装备者不同元素类型的角色，元素精通提升50点。上述每类效果至多计算3个角色。该效果每8秒至多触发一次。装备者处于队伍后台时，依然能触发该效果。"
        ]
      }
    },
    "deepwood_memories": {
      "name": {
        "en": "Deepwood Memories",
        "zh": "深林的记忆"
      },
      "effects": {
        "en": [
          "Dendro DMG Bonus +15%.",
          "After Elemental Skills or Bursts hit opponents, the targets' Dendro RES will be decreased by 30% for 8s. This effect can be triggered even if the equipping character is not on the field."
        ],
        "zh": [
          "获得15%草元素伤害加成",
          "元素战技或元素爆发命中敌人后，使命中目标的草元素抗性降低30%，持续8秒。装备者处于队伍后台时，依然能触发该效果。"
        ]
      }
    },
    "retracing_bolide": {
      "name": {
        "en": "Retracing Bolide",
        "zh": "逆飞的流星"
      },
      "effects": {
        "en": [
          "Increases Shield Strength by 35%.",
          "While protected by a shield, gain an additional 40% Normal and Charged Attack DMG."
        ],
        "zh": [
          "护盾强效提高35%。",
          "处于护盾庇护下时，额外获得40%普通攻击和重击伤害加成。"
        ]
      }
    },
    "shimenawas_reminiscence": {
      "name": {
        "en": "Shimenawa's Reminiscence",
        "zh": "追忆之注连"
      },
      "effects": {
        "en": [
          "ATK +18%.",
          "When casting an Elemental Skill, if the character has 15 or more Energy, they lose 15 Energy and Normal/Charged/Plunging Attack DMG is increased by 50% for 10s. This effect will not trigger again during that duration."
        ],
        "zh": [
          "攻击力提高18%。",
          "施放元素战技时，如果角色的元素能量高于或等于15点，则会流失15点元素能量，使接下来的10秒内，普通攻击、重击、下落攻击造成的伤害提高50%，持续期间内该效果不会再次触发。"
        ]
      }
    },
    "vermillion_hereafter": {
      "name": {
        "en": "Vermillion Hereafter",
        "zh": "辰砂往生录"
      },
      "effects": {
        "en": [
          "ATK +18%.",
          "After using an Elemental Burst, this character will gain the Nascent Light effect, increasing their ATK by 8% for 16s. When the character's HP decreases, their ATK will further increase by 10%. This further increase can occur this way a maximum of 4 times. This effect can be triggered once every 0.8s. Nascent Light will be dispelled when the character leaves the field. If an Elemental Burst is used again during the duration of Nascent Light, the original Nascent Light will be dispelled."
        ],
        "zh": [
          "攻击力提高18%。",
          "施放元素爆发后，将产生持续16秒的「潜光」效果：攻击力提升8%；并在角色的生命值降低时，攻击力进一步提升10%，至多通过这种方式提升4次，每0.8秒至多触发一次。「潜光」效果将在角色退场时消失；持续期间再次施放元素爆发，将移除原有的「潜光」。"
        ]
      }
    },
    "gladiators_finale": {
      "name": {
        "en": "Gladiator's Finale",
        "zh": "角斗士的终幕礼"
      },
      "effects": {
        "en": [
          "ATK +18%.",
          "If the wielder of this artifact set uses a Sword, Claymore or Polearm, increases their Normal Attack DMG by 35%."
        ],
        "zh": [
          "攻击力提高18%。",
          "装备该圣遗物套装的角色为单手剑、双手剑、长柄武器角色时，角色普通攻击造成的伤害提高35%。"
        ]
      }
    },
    "maiden_beloved": {
      "name": {
        "en": "Maiden Beloved",
        "zh": "被怜爱的少女"
      },
      "effects": {
        "en": [
          "Character Healing Effectiveness +15%",
          "Using an Elemental Skill or Burst increases healing received by all party members by 20% for 10s."
        ],
        "zh": [
          "角色造成的治疗效果提升15%。",
          "施放元素战技或元素爆发后的10秒内，队伍中所有角色受治疗效果加成提高20%。"
        ]
      }
    },
    "pale_flame": {
      "name": {
        "en": "Pale Flame",
        "zh": "苍白之火"
      },
      "effects": {
        "en": [
          "Physical DMG is increased by 25%.",
          "When an Elemental Skill hits an opponent, ATK is increased by 9% for 7s. This effect stacks up to 2 times and can be triggered once every 0.3s. Once 2 stacks are reached, the 2-set effect is increased by 100%."
        ],
        "zh": [
          "造成的物理伤害提高25%。",
          "元素战技命中敌人后，攻击力提升9%。该效果持续7秒，至多叠加2层，每0.3秒至多触发一次。叠满2层时，2件套的效果提升100%。"
        ]
      }
    },
    "viridescent_venerer": {
      "name": {
        "en": "Viridescent Venerer",
        "zh": "翠绿之影"
      },
      "effects": {
        "en": [
          "Anemo DMG Bonus +15%",
          "Increases Swirl DMG by 60%. Decreases opponent's Elemental RES to the element infused in the Swirl by 40% for 10s."
        ],
        "zh": [
          "获得15%风元素伤害加成。",
          "扩散反应造成的伤害提升60%。根据扩散的元素类型，降低受到影响的敌人40%的对应元素抗性，持续10秒。"
        ]
      }
    },
    "emblem_of_severed_fate": {
      "name": {
        "en": "Emblem of Severed Fate",
        "zh": "绝缘之旗印"
      },
      "effects": {
        "en": [
          "Energy Recharge +20%",
          "Increases Elemental Burst DMG by 25% of Energy Recharge. A maximum of 75% bonus DMG can be obtained in this way."
        ],
        "zh": [
          "元素充能效率提高20%。",
          "基于元素充能效率的25%，提高元素爆发造成的伤害。至多通过这种方式获得75%提升。"
        ]
      }
    },
    "crimson_witch_of_flames": {
      "name": {
        "en": "Crimson Witch of Flames",
        "zh": "炽烈的炎之魔女"
      },
      "effects": {
        "en": [
          "Pyro DMG Bonus +15%",
          "Increases Overloaded and Burning DMG by 40%. Increases Vaporize and Melt DMG by 15%. Using Elemental Skill increases the 2-Piece Set Bonus by 50% of its starting value for 10s. Max 3 stacks."
        ],
        "zh": [
          "获得15%火元素伤害加成。",
          "超载、燃烧、烈绽放反应造成的伤害提升40%，蒸发、融化反应的加成系数提高15%。施放元素战技后的10秒内，二件套的效果提高50%，该效果最多叠加3次。"
        ]
      }
    },
    "lavawalker": {
      "name": {
        "en": "Lavawalker",
        "zh": "渡过烈火的贤人"
      },
      "effects": {
        "en": [
          "Pyro RES increased by 40%.",
          "Increases DMG against opponents affected by Pyro by 35%."
        ],
        "zh": [
          "火元素抗性提高40%。",
          "对处于火元素影响下的敌人造成的伤害提升35%。"
        ]
      }
    },
    "oceanhued_clam": {
      "name": {
        "en": "Ocean-Hued Clam",
        "zh": "海染砗磲"
      },
      "effects": {
        "en": [
          "Healing Bonus +15%.",
          "When the character equipping this artifact set heals a character in the party, a Sea-Dyed Foam will appear for 3 seconds, accumulating the amount of HP recovered from healing (including overflow healing). At the end of the duration, the Sea-Dyed Foam will explode, dealing DMG to nearby opponents based on 90% of the accumulated healing. (This DMG is calculated similarly to Reactions such as Electro-Charged, and Superconduct, but is not affected by Elemental Mastery, Character Levels, or Reaction DMG Bonuses). Only one Sea-Dyed Foam can be produced every 3.5 seconds. Each Sea-Dyed Foam can accumulate up to 30,000 HP (including overflow healing). There can be no more than one Sea-Dyed Foam active at any given time. This effect can still be triggered even when the character who is using this artifact set is not on the field."
        ],
        "zh": [
          "治疗加成提高15%。",
          "装备此圣遗物套装的角色对队伍中的角色进行治疗时，将产生持续3秒的海染泡沫，记录治疗的生命值回复量（包括溢出值）。持续时间结束时，海染泡沫将会爆炸，对周围的敌人造成90%累计回复量的伤害（该伤害结算方式同感电、超导等元素反应，但不受元素精通、等级或反应伤害加成效果影响）。每3.5秒至多产生一个海染泡沫；海染泡沫至多记录30000点回复量，含溢出部分的治疗量；自己的队伍中同时至多存在一个海染泡沫。装备此圣遗物套装的角色处于队伍后台时，依然能触发该效果。"
        ]
      }
    },
    "wanderers_troupe": {
      "name": {
        "en": "Wanderer's Troupe",
        "zh": "流浪大地的乐团"
      },
      "effects": {
        "en": [
          "Increases Elemental Mastery by 80.",
          "Increases Charged Attack DMG by 35% if the character uses a Catalyst or a Bow."
        ],
        "zh": [
          "元素精通提高80点。",
          "装备该圣遗物套装的角色为法器、弓箭角色时，角色重击造成的伤害提高35%。"
        ]
      }
    },
    "heart_of_depth": {
      "name": {
        "en": "Heart of Depth",
        "zh": "沉沦之心"
      },
      "effects": {
        "en": [
          "Hydro DMG Bonus +15%",
          "After using Elemental Skill, increases Normal Attack and Charged Attack DMG by 30% for 15s."
        ],
        "zh": [
          "获得15%水元素伤害加成。",
          "施放元素战技后的15秒内，普通攻击与重击造成的伤害提高30%。"
        ]
      }
    },
    "bloodstained_chivalry": {
      "name": {
        "en": "Bloodstained Chivalry",
        "zh": "染血的骑士道"
      },
      "effects": {
        "en": [
          "Physical DMG +25%",
          "After defeating an opponent, increases Charged Attack DMG by 50%, and reduces its Stamina cost to 0 for 10s."
        ],
        "zh": [
          "造成的物理伤害提高25%。",
          "击败敌人后的10秒内，施放重击时不消耗体力，且重击造成的伤害提升50%。"
        ]
      }
    },
    "echoes_of_an_offering": {
      "name": {
        "en": "Echoes of an Offering",
        "zh": "来歆余响"
      },
      "effects": {
        "en": [
          "ATK +18%.",
          "When Normal Attacks hit opponents, there is a 36% chance that it will trigger Valley Rite, which will increase Normal Attack DMG by 70% of ATK. This effect will be dispelled 0.05s after a Normal Attack deals DMG. If a Normal Attack fails to trigger Valley Rite, the odds of it triggering the next time will increase by 20%. This trigger can occur once every 0.2s."
        ],
        "zh": [
          "攻击力提高18%。",
          "普通攻击命中敌人时，有36%概率触发「幽谷祝祀」：普通攻击造成的伤害提高，伤害提高值为攻击力的70%，该效果将在普通攻击造成伤害后的0.05秒后清除。普通攻击未触发「幽谷祝祀」时，会使下次触发概率提升20%；0.2秒内至多判定1次触发与否。"
        ]
      }
    },
    "noblesse_oblige": {
      "name": {
        "en": "Noblesse Oblige",
        "zh": "昔日宗室之仪"
      },
      "effects": {
        "en": [
          "Elemental Burst DMG +20%",
          "Using an Elemental Burst increases all party members' ATK by 20% for 12s. This effect cannot stack."
        ],
        "zh": [
          "元素爆发造成的伤害提升20%。",
          "施放元素爆发后，队伍中所有角色攻击力提升20%，持续12秒。该效果不可叠加。"
        ]
      }
    },
    "instructor": {
      "name": {
        "en": "Instructor",
        "zh": "教官"
      },
      "effects": {
        "en": [
          "Increases Elemental Mastery by 80.",
          "Upon triggering an Elemental Reaction, increases all party members' Elemental Mastery by 120 for 8s."
        ],
        "zh": [
          "元素精通提高80点。",
          "触发元素反应后，队伍中所有角色的元素精通提高120点，持续8秒。"
        ]
      }
    },
    "archaic_petra": {
      "name": {
        "en": "Archaic Petra",
        "zh": "悠古的磐岩"
      },
      "effects": {
        "en": [
          "Gain a 15% Geo DMG Bonus.",
          "Upon obtaining an Elemental Shard created through a Crystallize Reaction, all party members gain a 35% DMG Bonus for that particular element for 10s. Only one form of Elemental DMG Bonus can be gained in this manner at any one time."
        ],
        "zh": [
          "获得15%岩元素伤害加成。",
          "获得结晶反应形成的晶片时，队伍中所有角色获得35%对应元素伤害加成，持续10秒。同时只能通过该效果获得一种元素伤害加成。"
        ]
      }
    },
    "thundersoother": {
      "name": {
        "en": "Thundersoother",
        "zh": "平息鸣雷的尊者"
      },
      "effects": {
        "en": [
          "Electro RES increased by 40%.",
          "Increases DMG against opponents affected by Electro by 35%."
        ],
        "zh": [
          "雷元素抗性提高40%。",
          "对处于雷元素影响下的敌人造成的伤害提升35%。"
        ]
      }
    },
    "thundering_fury": {
      "name": {
        "en": "Thundering Fury",
        "zh": "如雷的盛怒"
      },
      "effects": {
        "en": [
          "Electro DMG Bonus +15%",
          "Increases the DMG caused by Overloaded, Electro-Charged, Superconduct, and Hyperbloom by 40%, the DMG Bonus conferred by Aggravate by 20%, and the DMG caused by Lunar-Charged by 20%. When Quicken or the aforementioned Elemental Reactions are triggered, Elemental Skill CD is decreased by 1s. Can only occur once every 0.8s."
        ],
        "zh": [
          "获得15%雷元素伤害加成。",
          "超载、感电、超导、超绽放反应造成的伤害提升40%，超激化反应带来的伤害提升提高20%。触发上述元素反应或原激化反应时，元素战技冷却时间减少1秒。该效果每0.8秒最多触发一次。"
        ]
      }
    },
    "husk_of_opulent_dreams": {
      "name": {
        "en": "Husk of Opulent Dreams",
        "zh": "华馆梦醒形骸记"
      },
      "effects": {
        "en": [
          "DEF +30%",
          "A character equipped with this Artifact set will obtain the Curiosity effect in the following conditions: When on the field, the character gains 1 stack after hitting an opponent with a Geo attack, triggering a maximum of once every 0.3s. When off the field, the character gains 1 stack every 3s. Curiosity can stack up to 4 times, each providing 6% DEF and a 6% Geo DMG Bonus. When 6 seconds pass without gaining a Curiosity stack, 1 stack is lost."
        ],
        "zh": [
          "防御力提高30%。",
          "装备此圣遗物套装的角色在以下情况下，将获得「问答」效果：在场上用岩元素攻击命中敌人后获得一层，每0.3秒至多触发一次；在队伍后台中，每3秒获得一层。问答至多叠加4层，每层能提供6%防御力与6%岩元素伤害加成。每6秒，若未获得问答效果，将损失一层。"
        ]
      }
    },
    "tenacity_of_the_millelith": {
      "name": {
        "en": "Tenacity of the Millelith",
        "zh": "千岩牢固"
      },
      "effects": {
        "en": [
          "HP increased by 20%.",
          "When an Elemental Skill hits an opponent, the ATK of all nearby party members is increased by 20% and their Shield Strength is increased by 30% for 3s. This effect can be triggered once every 0.5s. This effect can still be triggered even when the character who is using this artifact set is not on the field."
        ],
        "zh": [
          "生命值提升20%",
          "元素战技命中敌人后，使队伍中附近的所有角色攻击力提升20%，护盾强效提升30%，持续3秒。该效果每0.5秒至多触发一次。装备此圣遗物套装的角色处于队伍后台时，依然能触发该效果。"
        ]
      }
    },
    "blizzard_strayer": {
      "name": {
        "en": "Blizzard Strayer",
        "zh": "冰风迷途的勇士"
      },
      "effects": {
        "en": [
          "Cryo DMG Bonus +15%",
          "When a character attacks an opponent affected by Cryo, their CRIT Rate is increased by 20%. If the opponent is Frozen, CRIT Rate is increased by an additional 20%."
        ],
        "zh": [
          "获得15%冰元素伤害加成。",
          "攻击处于冰元素影响下的敌人时，暴击率提高20%；若敌人处于冻结状态下，则暴击率额外提高20%。"
        ]
      }
    }
  },
  "weapons": {
    "the_daybreak_chronicles": {
      "en": "The Daybreak Chronicles",
      "zh": "黎明破晓之史"
    },
    "athame_artis": {
      "en": "Athame Artis",
      "zh": "黑蚀"
    },
    "reliquary_of_truth": {
      "en": "Reliquary of Truth",
      "zh": "真语秘匣"
    },
    "dawning_frost": {
      "en": "Dawning Frost",
      "zh": "霜辰"
    },
    "sacrificers_staff": {
      "en": "Sacrificer's Staff",
      "zh": "圣祭者的辉杖"
    },
    "bloodsoaked_ruins": {
      "en": "Bloodsoaked Ruins",
      "zh": "血染荒城"
    },
    "etherlight_spindlelute": {
      "en": "Etherlight Spindlelute",
      "zh": "天光的纺琴"
    },
    "nightweavers_looking_glass": {
      "en": "Nightweaver's Looking Glass",
      "zh": "纺夜天镜"
    },
    "snare_hook": {
      "en": "Snare Hook",
      "zh": "罗网勾针"
    },
    "blackmarrow_lantern": {
      "en": "Blackmarrow Lantern",
      "zh": "乌髓孑灯"
    },
    "prospectors_shovel": {
      "en": "Prospector's Shovel",
      "zh": "掘金之锹"
    },
    "master_key": {
      "en": "Master Key",
      "zh": "万能钥匙"
    },
    "moonweavers_dawn": {
      "en": "Moonweaver's Dawn",
      "zh": "织月者的曙色"
    },
    "serenitys_call": {
      "en": "Serenity's Call",
      "zh": "谧音吹哨"
    },
    "flameforged_insight": {
      "en": "Flame-Forged Insight",
      "zh": "拾慧铸熔"
    },
    "fractured_halo": {
      "en": "Fractured Halo",
      "zh": "支离轮光"
    },
    "azurelight": {
      "en": "Azurelight",
      "zh": "苍耀"
    },
    "sequence_of_solitude": {
      "en": "Sequence of Solitude",
      "zh": "冷寂迸音"
    },
    "symphonist_of_scents": {
      "en": "Symphonist of Scents",
      "zh": "香韵奏者"
    },
    "vivid_notions": {
      "en": "Vivid Notions",
      "zh": "溢彩心念"
    },
    "tamayuratei_no_ohanashi": {
      "en": "Tamayuratei no Ohanashi",
      "zh": "且住亭御咄"
    },
    "sunny_morning_sleepin": {
      "en": "Sunny Morning Sleep-In",
      "zh": "寝正月初晴"
    },
    "starcallers_watch": {
      "en": "Starcaller's Watch",
      "zh": "祭星者之望"
    },
    "a_thousand_blazing_suns": {
      "en": "A Thousand Blazing Suns",
      "zh": "焚曜千阳"
    },
    "astral_vultures_crimson_plumage": {
      "en": "Astral Vulture's Crimson Plumage",
      "zh": "星鹫赤羽"
    },
    "flowerwreathed_feathers": {
      "en": "Flower-Wreathed Feathers",
      "zh": "缀花之翎"
    },
    "waveriding_whirl": {
      "en": "Waveriding Whirl",
      "zh": "乘浪的回旋"
    },
    "calamity_of_eshu": {
      "en": "Calamity of Eshu",
      "zh": "厄水之祸"
    },
    "mountainbracing_bolt": {
      "en": "Mountain-Bracing Bolt",
      "zh": "镇山之钉"
    },
    "fruitful_hook": {
      "en": "Fruitful Hook",
      "zh": "硕果钩"
    },
    "peak_patrol_song": {
      "en": "Peak Patrol Song",
      "zh": "岩峰巡歌"
    },
    "sturdy_bone": {
      "en": "Sturdy Bone",
      "zh": "弥坚骨"
    },
    "chain_breaker": {
      "en": "Chain Breaker",
      "zh": "碎链"
    },
    "ring_of_yaxche": {
      "en": "Ring of Yaxche",
      "zh": "木棉之环"
    },
    "ashgraven_drinking_horn": {
      "en": "Ash-Graven Drinking Horn",
      "zh": "苍纹角杯"
    },
    "footprint_of_the_rainbow": {
      "en": "Footprint of the Rainbow",
      "zh": "虹的行迹"
    },
    "earth_shaker": {
      "en": "Earth Shaker",
      "zh": "撼地者"
    },
    "flute_of_ezpitzal": {
      "en": "Flute of Ezpitzal",
      "zh": "息燧之笛"
    },
    "surfs_up": {
      "en": "Surf's Up",
      "zh": "冲浪时光"
    },
    "fang_of_the_mountain_king": {
      "en": "Fang of the Mountain King",
      "zh": "山王长牙"
    },
    "lumidouce_elegy": {
      "en": "Lumidouce Elegy",
      "zh": "柔灯挽歌"
    },
    "cloudforged": {
      "en": "Cloudforged",
      "zh": "筑云"
    },
    "absolution": {
      "en": "Absolution",
      "zh": "赦罪"
    },
    "silvershower_heartstrings": {
      "en": "Silvershower Heartstrings",
      "zh": "白雨心弦"
    },
    "crimson_moons_semblance": {
      "en": "Crimson Moon’s Semblance",
      "zh": "赤月之形"
    },
    "dialogues_of_the_desert_sages": {
      "en": "Dialogues of the Desert Sages",
      "zh": "沙中伟贤的对答"
    },
    "uraku_misugiri": {
      "en": "Uraku Misugiri",
      "zh": "有乐御簾切"
    },
    "cranes_echoing_call": {
      "en": "Crane's Echoing Call",
      "zh": "鹤鸣余音"
    },
    "ultimate_overlords_mega_magic_sword": {
      "en": "Ultimate Overlord's Mega Magic Sword",
      "zh": "究极霸王超级魔剑"
    },
    "verdict": {
      "en": "Verdict",
      "zh": "裁断"
    },
    "sword_of_narzissenkreuz": {
      "en": "Sword of Narzissenkreuz",
      "zh": "水仙十字之剑"
    },
    "splendor_of_tranquil_waters": {
      "en": "Splendor of Tranquil Waters",
      "zh": "静水流涌之辉"
    },
    "cashflow_supervision": {
      "en": "Cashflow Supervision",
      "zh": "金流监督"
    },
    "tome_of_the_eternal_flow": {
      "en": "Tome of the Eternal Flow",
      "zh": "万世流涌大典"
    },
    "ballad_of_the_boundless_blue": {
      "en": "Ballad of the Boundless Blue",
      "zh": "无垠蔚蓝之歌"
    },
    "range_gauge": {
      "en": "Range Gauge",
      "zh": "测距规"
    },
    "prospectors_drill": {
      "en": "Prospector's Drill",
      "zh": "勘探钻机"
    },
    "portable_power_saw": {
      "en": "Portable Power Saw",
      "zh": "便携动力锯"
    },
    "the_dockhands_assistant": {
      "en": "The Dockhand's Assistant",
      "zh": "船坞长剑"
    },
    "sacrificial_jade": {
      "en": "Sacrificial Jade",
      "zh": "遗祀玉珑"
    },
    "scion_of_the_blazing_sun": {
      "en": "Scion of the Blazing Sun",
      "zh": "烈阳之嗣"
    },
    "ballad_of_the_fjords": {
      "en": "Ballad of the Fjords",
      "zh": "峡湾长歌"
    },
    "talking_stick": {
      "en": "Talking Stick",
      "zh": "聊聊棒"
    },
    "wolffang": {
      "en": "Wolf-Fang",
      "zh": "狼牙"
    },
    "fleuve_cendre_ferryman": {
      "en": "Fleuve Cendre Ferryman",
      "zh": "灰河渡手"
    },
    "flowing_purity": {
      "en": "Flowing Purity",
      "zh": "纯水流华"
    },
    "song_of_stillness": {
      "en": "Song of Stillness",
      "zh": "静谧之曲"
    },
    "rightful_reward": {
      "en": "Rightful Reward",
      "zh": "公义的酬报"
    },
    "tidal_shadow": {
      "en": "Tidal Shadow",
      "zh": "浪影阔剑"
    },
    "finale_of_the_deep": {
      "en": "Finale of the Deep",
      "zh": "海渊终曲"
    },
    "the_first_great_magic": {
      "en": "The First Great Magic",
      "zh": "最初的大魔术"
    },
    "ibis_piercer": {
      "en": "Ibis Piercer",
      "zh": "鹮穿之喙"
    },
    "jadefalls_splendor": {
      "en": "Jadefall's Splendor",
      "zh": "碧落之珑"
    },
    "beacon_of_the_reed_sea": {
      "en": "Beacon of the Reed Sea",
      "zh": "苇海信标"
    },
    "mailed_flower": {
      "en": "Mailed Flower",
      "zh": "饰铁之花"
    },
    "light_of_foliar_incision": {
      "en": "Light of Foliar Incision",
      "zh": "裁叶萃光"
    },
    "tulaytullahs_remembrance": {
      "en": "Tulaytullah's Remembrance",
      "zh": "图莱杜拉的回忆"
    },
    "toukabou_shigure": {
      "en": "Toukabou Shigure",
      "zh": "东花坊时雨"
    },
    "a_thousand_floating_dreams": {
      "en": "A Thousand Floating Dreams",
      "zh": "千夜浮梦"
    },
    "wandering_evenstar": {
      "en": "Wandering Evenstar",
      "zh": "流浪的晚星"
    },
    "xiphos_moonlight": {
      "en": "Xiphos' Moonlight",
      "zh": "西福斯的月光"
    },
    "key_of_khajnisut": {
      "en": "Key of Khaj-Nisut",
      "zh": "圣显之钥"
    },
    "staff_of_the_scarlet_sands": {
      "en": "Staff of the Scarlet Sands",
      "zh": "赤沙之杖"
    },
    "makhaira_aquamarine": {
      "en": "Makhaira Aquamarine",
      "zh": "玛海菈的水色"
    },
    "missive_windspear": {
      "en": "Missive Windspear",
      "zh": "风信之锋"
    },
    "forest_regalia": {
      "en": "Forest Regalia",
      "zh": "森林王器"
    },
    "kings_squire": {
      "en": "King's Squire",
      "zh": "王下近侍"
    },
    "fruit_of_fulfillment": {
      "en": "Fruit of Fulfillment",
      "zh": "盈满之实"
    },
    "moonpiercer": {
      "en": "Moonpiercer",
      "zh": "贯月矢"
    },
    "sapwood_blade": {
      "en": "Sapwood Blade",
      "zh": "原木刀"
    },
    "end_of_the_line": {
      "en": "End of the Line",
      "zh": "竭泽"
    },
    "hunters_path": {
      "en": "Hunter's Path",
      "zh": "猎人之径"
    },
    "kagotsurube_isshin": {
      "en": "Kagotsurube Isshin",
      "zh": "笼钓瓶一心"
    },
    "fading_twilight": {
      "en": "Fading Twilight",
      "zh": "落霞"
    },
    "aqua_simulacra": {
      "en": "Aqua Simulacra",
      "zh": "若水"
    },
    "dragonspine_spear": {
      "en": "Dragonspine Spear",
      "zh": "龙脊长枪"
    },
    "black_tassel": {
      "en": "Black Tassel",
      "zh": "黑缨枪"
    },
    "blackcliff_longsword": {
      "en": "Blackcliff Longsword",
      "zh": "黑岩长剑"
    },
    "blackcliff_agate": {
      "en": "Blackcliff Agate",
      "zh": "黑岩绯玉"
    },
    "blackcliff_slasher": {
      "en": "Blackcliff Slasher",
      "zh": "黑岩斩刀"
    },
    "blackcliff_warbow": {
      "en": "Blackcliff Warbow",
      "zh": "黑岩战弓"
    },
    "blackcliff_pole": {
      "en": "Blackcliff Pole",
      "zh": "黑岩刺枪"
    },
    "the_black_sword": {
      "en": "The Black Sword",
      "zh": "黑剑"
    },
    "harbinger_of_dawn": {
      "en": "Harbinger of Dawn",
      "zh": "黎明神剑"
    },
    "raven_bow": {
      "en": "Raven Bow",
      "zh": "鸦羽弓"
    },
    "magic_guide": {
      "en": "Magic Guide",
      "zh": "魔导绪论"
    },
    "thundering_pulse": {
      "en": "Thundering Pulse",
      "zh": "飞雷之弦振"
    },
    "skyrider_sword": {
      "en": "Skyrider Sword",
      "zh": "飞天御剑"
    },
    "skyrider_greatsword": {
      "en": "Skyrider Greatsword",
      "zh": "飞天大御剑"
    },
    "aquila_favonia": {
      "en": "Aquila Favonia",
      "zh": "风鹰剑"
    },
    "windblume_ode": {
      "en": "Windblume Ode",
      "zh": "风花之颂"
    },
    "mistsplitter_reforged": {
      "en": "Mistsplitter Reforged",
      "zh": "雾切之回光"
    },
    "snowtombed_starsilver": {
      "en": "Snow-Tombed Starsilver",
      "zh": "雪葬的星银"
    },
    "rainslasher": {
      "en": "Rainslasher",
      "zh": "雨裁"
    },
    "sword_of_descension": {
      "en": "Sword of Descension",
      "zh": "降临之剑"
    },
    "amos_bow": {
      "en": "Amos' Bow",
      "zh": "阿莫斯之弓"
    },
    "silver_sword": {
      "en": "Silver Sword",
      "zh": "银剑"
    },
    "iron_sting": {
      "en": "Iron Sting",
      "zh": "铁蜂刺"
    },
    "ferrous_shadow": {
      "en": "Ferrous Shadow",
      "zh": "铁影阔剑"
    },
    "iron_point": {
      "en": "Iron Point",
      "zh": "铁尖枪"
    },
    "halberd": {
      "en": "Halberd",
      "zh": "钺矛"
    },
    "compound_bow": {
      "en": "Compound Bow",
      "zh": "钢轮弓"
    },
    "the_bell": {
      "en": "The Bell",
      "zh": "钟剑"
    },
    "cinnabar_spindle": {
      "en": "Cinnabar Spindle",
      "zh": "辰砂之纺锤"
    },
    "redhorn_stonethresher": {
      "en": "Redhorn Stonethresher",
      "zh": "赤角石溃杵"
    },
    "vortex_vanquisher": {
      "en": "Vortex Vanquisher",
      "zh": "贯虹之槊"
    },
    "prototype_amber": {
      "en": "Prototype Amber",
      "zh": "试作金珀"
    },
    "prototype_crescent": {
      "en": "Prototype Crescent",
      "zh": "试作澹月"
    },
    "prototype_starglitter": {
      "en": "Prototype Starglitter",
      "zh": "试作星镰"
    },
    "prototype_rancour": {
      "en": "Prototype Rancour",
      "zh": "试作斩岩"
    },
    "prototype_archaic": {
      "en": "Prototype Archaic",
      "zh": "试作古华"
    },
    "oathsworn_eye": {
      "en": "Oathsworn Eye",
      "zh": "证誓之明瞳"
    },
    "waster_greatsword": {
      "en": "Waster Greatsword",
      "zh": "训练大剑"
    },
    "thrilling_tales_of_dragon_slayers": {
      "en": "Thrilling Tales of Dragon Slayers",
      "zh": "讨龙英杰谭"
    },
    "favonius_lance": {
      "en": "Favonius Lance",
      "zh": "西风长枪"
    },
    "favonius_codex": {
      "en": "Favonius Codex",
      "zh": "西风秘典"
    },
    "favonius_warbow": {
      "en": "Favonius Warbow",
      "zh": "西风猎弓"
    },
    "favonius_greatsword": {
      "en": "Favonius Greatsword",
      "zh": "西风大剑"
    },
    "favonius_sword": {
      "en": "Favonius Sword",
      "zh": "西风剑"
    },
    "luxurious_sealord": {
      "en": "Luxurious Sea-Lord",
      "zh": "衔珠海皇"
    },
    "serpent_spine": {
      "en": "Serpent Spine",
      "zh": "螭骨剑"
    },
    "engulfing_lightning": {
      "en": "Engulfing Lightning",
      "zh": "薙草之稻光"
    },
    "the_viridescent_hunt": {
      "en": "The Viridescent Hunt",
      "zh": "苍翠猎弓"
    },
    "freedomsworn": {
      "en": "Freedom-Sworn",
      "zh": "苍古自由之誓"
    },
    "festering_desire": {
      "en": "Festering Desire",
      "zh": "腐殖之剑"
    },
    "emerald_orb": {
      "en": "Emerald Orb",
      "zh": "翡玉法球"
    },
    "the_stringless": {
      "en": "The Stringless",
      "zh": "绝弦"
    },
    "elegy_for_the_end": {
      "en": "Elegy for the End",
      "zh": "终末嗟叹之诗"
    },
    "the_flute": {
      "en": "The Flute",
      "zh": "笛剑"
    },
    "sacrificial_fragments": {
      "en": "Sacrificial Fragments",
      "zh": "祭礼残章"
    },
    "sacrificial_bow": {
      "en": "Sacrificial Bow",
      "zh": "祭礼弓"
    },
    "sacrificial_greatsword": {
      "en": "Sacrificial Greatsword",
      "zh": "祭礼大剑"
    },
    "sacrificial_sword": {
      "en": "Sacrificial Sword",
      "zh": "祭礼剑"
    },
    "sharpshooters_oath": {
      "en": "Sharpshooter's Oath",
      "zh": "神射手之誓"
    },
    "kaguras_verity": {
      "en": "Kagura's Verity",
      "zh": "神乐之真意"
    },
    "primordial_jade_cutter": {
      "en": "Primordial Jade Cutter",
      "zh": "磐岩结绿"
    },
    "hamayumi": {
      "en": "Hamayumi",
      "zh": "破魔之弓"
    },
    "white_iron_greatsword": {
      "en": "White Iron Greatsword",
      "zh": "白铁大剑"
    },
    "hakushin_ring": {
      "en": "Hakushin Ring",
      "zh": "白辰之环"
    },
    "white_tassel": {
      "en": "White Tassel",
      "zh": "白缨枪"
    },
    "whiteblind": {
      "en": "Whiteblind",
      "zh": "白影剑"
    },
    "twin_nephrite": {
      "en": "Twin Nephrite",
      "zh": "甲级宝珏"
    },
    "hunters_bow": {
      "en": "Hunter's Bow",
      "zh": "猎弓"
    },
    "wolfs_gravestone": {
      "en": "Wolf's Gravestone",
      "zh": "狼的末路"
    },
    "the_widsith": {
      "en": "The Widsith",
      "zh": "流浪乐章"
    },
    "crescent_pike": {
      "en": "Crescent Pike",
      "zh": "流月针"
    },
    "haran_geppaku_futsu": {
      "en": "Haran Geppaku Futsu",
      "zh": "波乱月白经津"
    },
    "bloodtainted_greatsword": {
      "en": "Bloodtainted Greatsword",
      "zh": "沐浴龙血的剑"
    },
    "katsuragikiri_nagamasa": {
      "en": "Katsuragikiri Nagamasa",
      "zh": "桂木斩长正"
    },
    "song_of_broken_pines": {
      "en": "Song of Broken Pines",
      "zh": "松籁响起之时"
    },
    "mouuns_moon": {
      "en": "Mouun's Moon",
      "zh": "曚云之月"
    },
    "dark_iron_sword": {
      "en": "Dark Iron Sword",
      "zh": "暗铁剑"
    },
    "the_alley_flash": {
      "en": "The Alley Flash",
      "zh": "暗巷闪光"
    },
    "wine_and_song": {
      "en": "Wine and Song",
      "zh": "暗巷的酒与诗"
    },
    "alley_hunter": {
      "en": "Alley Hunter",
      "zh": "暗巷猎手"
    },
    "eye_of_perception": {
      "en": "Eye of Perception",
      "zh": "昭心"
    },
    "dull_blade": {
      "en": "Dull Blade",
      "zh": "无锋剑"
    },
    "the_unforged": {
      "en": "The Unforged",
      "zh": "无工之剑"
    },
    "travelers_handy_sword": {
      "en": "Traveler's Handy Sword",
      "zh": "旅行剑"
    },
    "beginners_protector": {
      "en": "Beginner's Protector",
      "zh": "新手长枪"
    },
    "wavebreakers_fin": {
      "en": "Wavebreaker's Fin",
      "zh": "断浪长鳍"
    },
    "summit_shaper": {
      "en": "Summit Shaper",
      "zh": "斫峰之刃"
    },
    "predator": {
      "en": "Predator",
      "zh": "掠食者"
    },
    "staff_of_homa": {
      "en": "Staff of Homa",
      "zh": "护摩之杖"
    },
    "akuoumaru": {
      "en": "Akuoumaru",
      "zh": "恶王丸"
    },
    "calamity_queller": {
      "en": "Calamity Queller",
      "zh": "息灾"
    },
    "frostbearer": {
      "en": "Frostbearer",
      "zh": "忍冬之果"
    },
    "slingshot": {
      "en": "Slingshot",
      "zh": "弹弓"
    },
    "rust": {
      "en": "Rust",
      "zh": "弓藏"
    },
    "otherworldly_story": {
      "en": "Otherworldly Story",
      "zh": "异世界行记"
    },
    "mitternachts_waltz": {
      "en": "Mitternachts Waltz",
      "zh": "幽夜华尔兹"
    },
    "memory_of_dust": {
      "en": "Memory of Dust",
      "zh": "尘世之锁"
    },
    "royal_bow": {
      "en": "Royal Bow",
      "zh": "宗室长弓"
    },
    "royal_longsword": {
      "en": "Royal Longsword",
      "zh": "宗室长剑"
    },
    "royal_grimoire": {
      "en": "Royal Grimoire",
      "zh": "宗室秘法录"
    },
    "royal_spear": {
      "en": "Royal Spear",
      "zh": "宗室猎枪"
    },
    "royal_greatsword": {
      "en": "Royal Greatsword",
      "zh": "宗室大剑"
    },
    "apprentices_notes": {
      "en": "Apprentice's Notes",
      "zh": "学徒笔记"
    },
    "skyward_spine": {
      "en": "Skyward Spine",
      "zh": "天空之脊"
    },
    "skyward_harp": {
      "en": "Skyward Harp",
      "zh": "天空之翼"
    },
    "skyward_atlas": {
      "en": "Skyward Atlas",
      "zh": "天空之卷"
    },
    "skyward_blade": {
      "en": "Skyward Blade",
      "zh": "天空之刃"
    },
    "skyward_pride": {
      "en": "Skyward Pride",
      "zh": "天空之傲"
    },
    "amenoma_kageuchi": {
      "en": "Amenoma Kageuchi",
      "zh": "天目影打刀"
    },
    "lost_prayer_to_the_sacred_winds": {
      "en": "Lost Prayer to the Sacred Winds",
      "zh": "四风原典"
    },
    "dodoco_tales": {
      "en": "Dodoco Tales",
      "zh": "嘟嘟可故事集"
    },
    "kitain_cross_spear": {
      "en": "Kitain Cross Spear",
      "zh": "喜多院十文字"
    },
    "primordial_jade_wingedspear": {
      "en": "Primordial Jade Winged-Spear",
      "zh": "和璞鸢"
    },
    "fillet_blade": {
      "en": "Fillet Blade",
      "zh": "吃虎鱼刀"
    },
    "pocket_grimoire": {
      "en": "Pocket Grimoire",
      "zh": "口袋魔导书"
    },
    "recurve_bow": {
      "en": "Recurve Bow",
      "zh": "反曲弓"
    },
    "seasoned_hunters_bow": {
      "en": "Seasoned Hunter's Bow",
      "zh": "历练的猎弓"
    },
    "lithic_spear": {
      "en": "Lithic Spear",
      "zh": "千岩长枪"
    },
    "lithic_blade": {
      "en": "Lithic Blade",
      "zh": "千岩古剑"
    },
    "lions_roar": {
      "en": "Lion's Roar",
      "zh": "匣里龙吟"
    },
    "dragons_bane": {
      "en": "Dragon's Bane",
      "zh": "匣里灭辰"
    },
    "solar_pearl": {
      "en": "Solar Pearl",
      "zh": "匣里日月"
    },
    "cool_steel": {
      "en": "Cool Steel",
      "zh": "冷刃"
    },
    "deathmatch": {
      "en": "Deathmatch",
      "zh": "决斗之枪"
    },
    "polar_star": {
      "en": "Polar Star",
      "zh": "冬极白星"
    },
    "messenger": {
      "en": "Messenger",
      "zh": "信使"
    },
    "old_mercs_pal": {
      "en": "Old Merc's Pal",
      "zh": "佣兵重剑"
    },
    "debate_club": {
      "en": "Debate Club",
      "zh": "以理服人"
    },
    "everlasting_moonglow": {
      "en": "Everlasting Moonglow",
      "zh": "不灭月华"
    },
    "mappa_mare": {
      "en": "Mappa Mare",
      "zh": "万国诸海图谱"
    },
    "the_catch": {
      "en": "\"The Catch\"",
      "zh": "「渔获」"
    }
  }
};
