// This file is auto-generated by scripts/codedump.py
// Do not edit this file directly

import { ArtifactHalfSet, ArtifactSetResource, CharacterResource, ElementResource, WeaponResource, WeaponTypeResource } from './types';

export const characters: CharacterResource[] = [
  {
    "id": "varka",
    "rarity": 5,
    "imagePath": "/character/varka.png"
  },
  {
    "id": "illuga",
    "rarity": 4,
    "imagePath": "/character/illuga.png"
  },
  {
    "id": "zibai",
    "rarity": 5,
    "imagePath": "/character/zibai.png"
  },
  {
    "id": "columbina",
    "rarity": 5,
    "imagePath": "/character/columbina.png"
  },
  {
    "id": "manekina_pyro",
    "rarity": 5,
    "imagePath": "/character/manekina.png"
  },
  {
    "id": "manekina_hydro",
    "rarity": 5,
    "imagePath": "/character/manekina.png"
  },
  {
    "id": "manekina_electro",
    "rarity": 5,
    "imagePath": "/character/manekina.png"
  },
  {
    "id": "manekina_cryo",
    "rarity": 5,
    "imagePath": "/character/manekina.png"
  },
  {
    "id": "manekina_anemo",
    "rarity": 5,
    "imagePath": "/character/manekina.png"
  },
  {
    "id": "manekina_dendro",
    "rarity": 5,
    "imagePath": "/character/manekina.png"
  },
  {
    "id": "manekina_geo",
    "rarity": 5,
    "imagePath": "/character/manekina.png"
  },
  {
    "id": "manekin_pyro",
    "rarity": 5,
    "imagePath": "/character/manekin.png"
  },
  {
    "id": "manekin_hydro",
    "rarity": 5,
    "imagePath": "/character/manekin.png"
  },
  {
    "id": "manekin_electro",
    "rarity": 5,
    "imagePath": "/character/manekin.png"
  },
  {
    "id": "manekin_cryo",
    "rarity": 5,
    "imagePath": "/character/manekin.png"
  },
  {
    "id": "manekin_anemo",
    "rarity": 5,
    "imagePath": "/character/manekin.png"
  },
  {
    "id": "manekin_dendro",
    "rarity": 5,
    "imagePath": "/character/manekin.png"
  },
  {
    "id": "manekin_geo",
    "rarity": 5,
    "imagePath": "/character/manekin.png"
  },
  {
    "id": "jahoda",
    "rarity": 4,
    "imagePath": "/character/jahoda.png"
  },
  {
    "id": "durin",
    "rarity": 5,
    "imagePath": "/character/durin.png"
  },
  {
    "id": "nefer",
    "rarity": 5,
    "imagePath": "/character/nefer.png"
  },
  {
    "id": "flins",
    "rarity": 5,
    "imagePath": "/character/flins.png"
  },
  {
    "id": "aino",
    "rarity": 4,
    "imagePath": "/character/aino.png"
  },
  {
    "id": "lauma",
    "rarity": 5,
    "imagePath": "/character/lauma.png"
  },
  {
    "id": "ineffa",
    "rarity": 5,
    "imagePath": "/character/ineffa.png"
  },
  {
    "id": "dahlia",
    "rarity": 4,
    "imagePath": "/character/dahlia.png"
  },
  {
    "id": "skirk",
    "rarity": 5,
    "imagePath": "/character/skirk.png"
  },
  {
    "id": "ifa",
    "rarity": 4,
    "imagePath": "/character/ifa.png"
  },
  {
    "id": "escoffier",
    "rarity": 5,
    "imagePath": "/character/escoffier.png"
  },
  {
    "id": "iansan",
    "rarity": 4,
    "imagePath": "/character/iansan.png"
  },
  {
    "id": "varesa",
    "rarity": 5,
    "imagePath": "/character/varesa.png"
  },
  {
    "id": "yumemizuki_mizuki",
    "rarity": 5,
    "imagePath": "/character/yumemizuki_mizuki.png"
  },
  {
    "id": "traveler_pyro",
    "rarity": 5,
    "imagePath": "/character/traveler.png"
  },
  {
    "id": "lan_yan",
    "rarity": 4,
    "imagePath": "/character/lan_yan.png"
  },
  {
    "id": "citlali",
    "rarity": 5,
    "imagePath": "/character/citlali.png"
  },
  {
    "id": "mavuika",
    "rarity": 5,
    "imagePath": "/character/mavuika.png"
  },
  {
    "id": "chasca",
    "rarity": 5,
    "imagePath": "/character/chasca.png"
  },
  {
    "id": "ororon",
    "rarity": 4,
    "imagePath": "/character/ororon.png"
  },
  {
    "id": "xilonen",
    "rarity": 5,
    "imagePath": "/character/xilonen.png"
  },
  {
    "id": "mualani",
    "rarity": 5,
    "imagePath": "/character/mualani.png"
  },
  {
    "id": "kachina",
    "rarity": 4,
    "imagePath": "/character/kachina.png"
  },
  {
    "id": "kinich",
    "rarity": 5,
    "imagePath": "/character/kinich.png"
  },
  {
    "id": "emilie",
    "rarity": 5,
    "imagePath": "/character/emilie.png"
  },
  {
    "id": "sethos",
    "rarity": 4,
    "imagePath": "/character/sethos.png"
  },
  {
    "id": "sigewinne",
    "rarity": 5,
    "imagePath": "/character/sigewinne.png"
  },
  {
    "id": "clorinde",
    "rarity": 5,
    "imagePath": "/character/clorinde.png"
  },
  {
    "id": "arlecchino",
    "rarity": 5,
    "imagePath": "/character/arlecchino.png"
  },
  {
    "id": "chiori",
    "rarity": 5,
    "imagePath": "/character/chiori.png"
  },
  {
    "id": "gaming",
    "rarity": 4,
    "imagePath": "/character/gaming.png"
  },
  {
    "id": "xianyun",
    "rarity": 5,
    "imagePath": "/character/xianyun.png"
  },
  {
    "id": "chevreuse",
    "rarity": 4,
    "imagePath": "/character/chevreuse.png"
  },
  {
    "id": "navia",
    "rarity": 5,
    "imagePath": "/character/navia.png"
  },
  {
    "id": "charlotte",
    "rarity": 4,
    "imagePath": "/character/charlotte.png"
  },
  {
    "id": "furina",
    "rarity": 5,
    "imagePath": "/character/furina.png"
  },
  {
    "id": "neuvillette",
    "rarity": 5,
    "imagePath": "/character/neuvillette.png"
  },
  {
    "id": "wriothesley",
    "rarity": 5,
    "imagePath": "/character/wriothesley.png"
  },
  {
    "id": "traveler_hydro",
    "rarity": 5,
    "imagePath": "/character/traveler.png"
  },
  {
    "id": "freminet",
    "rarity": 4,
    "imagePath": "/character/freminet.png"
  },
  {
    "id": "lyney",
    "rarity": 5,
    "imagePath": "/character/lyney.png"
  },
  {
    "id": "lynette",
    "rarity": 4,
    "imagePath": "/character/lynette.png"
  },
  {
    "id": "kirara",
    "rarity": 4,
    "imagePath": "/character/kirara.png"
  },
  {
    "id": "baizhu",
    "rarity": 5,
    "imagePath": "/character/baizhu.png"
  },
  {
    "id": "kaveh",
    "rarity": 4,
    "imagePath": "/character/kaveh.png"
  },
  {
    "id": "dehya",
    "rarity": 5,
    "imagePath": "/character/dehya.png"
  },
  {
    "id": "mika",
    "rarity": 4,
    "imagePath": "/character/mika.png"
  },
  {
    "id": "alhaitham",
    "rarity": 5,
    "imagePath": "/character/alhaitham.png"
  },
  {
    "id": "yaoyao",
    "rarity": 4,
    "imagePath": "/character/yaoyao.png"
  },
  {
    "id": "wanderer",
    "rarity": 5,
    "imagePath": "/character/wanderer.png"
  },
  {
    "id": "faruzan",
    "rarity": 4,
    "imagePath": "/character/faruzan.png"
  },
  {
    "id": "layla",
    "rarity": 4,
    "imagePath": "/character/layla.png"
  },
  {
    "id": "nahida",
    "rarity": 5,
    "imagePath": "/character/nahida.png"
  },
  {
    "id": "candace",
    "rarity": 4,
    "imagePath": "/character/candace.png"
  },
  {
    "id": "cyno",
    "rarity": 5,
    "imagePath": "/character/cyno.png"
  },
  {
    "id": "nilou",
    "rarity": 5,
    "imagePath": "/character/nilou.png"
  },
  {
    "id": "traveler_dendro",
    "rarity": 5,
    "imagePath": "/character/traveler.png"
  },
  {
    "id": "dori",
    "rarity": 4,
    "imagePath": "/character/dori.png"
  },
  {
    "id": "collei",
    "rarity": 4,
    "imagePath": "/character/collei.png"
  },
  {
    "id": "tighnari",
    "rarity": 5,
    "imagePath": "/character/tighnari.png"
  },
  {
    "id": "shikanoin_heizou",
    "rarity": 4,
    "imagePath": "/character/shikanoin_heizou.png"
  },
  {
    "id": "kuki_shinobu",
    "rarity": 4,
    "imagePath": "/character/kuki_shinobu.png"
  },
  {
    "id": "yelan",
    "rarity": 5,
    "imagePath": "/character/yelan.png"
  },
  {
    "id": "xiao",
    "rarity": 5,
    "imagePath": "/character/xiao.png"
  },
  {
    "id": "xiangling",
    "rarity": 4,
    "imagePath": "/character/xiangling.png"
  },
  {
    "id": "raiden_shogun",
    "rarity": 5,
    "imagePath": "/character/raiden_shogun.png"
  },
  {
    "id": "razor",
    "rarity": 4,
    "imagePath": "/character/razor.png"
  },
  {
    "id": "albedo",
    "rarity": 5,
    "imagePath": "/character/albedo.png"
  },
  {
    "id": "zhongli",
    "rarity": 5,
    "imagePath": "/character/zhongli.png"
  },
  {
    "id": "chongyun",
    "rarity": 4,
    "imagePath": "/character/chongyun.png"
  },
  {
    "id": "diona",
    "rarity": 4,
    "imagePath": "/character/diona.png"
  },
  {
    "id": "diluc",
    "rarity": 5,
    "imagePath": "/character/diluc.png"
  },
  {
    "id": "tartaglia",
    "rarity": 5,
    "imagePath": "/character/tartaglia.png"
  },
  {
    "id": "xinyan",
    "rarity": 4,
    "imagePath": "/character/xinyan.png"
  },
  {
    "id": "noelle",
    "rarity": 4,
    "imagePath": "/character/noelle.png"
  },
  {
    "id": "xingqiu",
    "rarity": 4,
    "imagePath": "/character/xingqiu.png"
  },
  {
    "id": "fischl",
    "rarity": 4,
    "imagePath": "/character/fischl.png"
  },
  {
    "id": "mona",
    "rarity": 5,
    "imagePath": "/character/mona.png"
  },
  {
    "id": "arataki_itto",
    "rarity": 5,
    "imagePath": "/character/arataki_itto.png"
  },
  {
    "id": "barbara",
    "rarity": 4,
    "imagePath": "/character/barbara.png"
  },
  {
    "id": "hu_tao",
    "rarity": 5,
    "imagePath": "/character/hu_tao.png"
  },
  {
    "id": "rosaria",
    "rarity": 4,
    "imagePath": "/character/rosaria.png"
  },
  {
    "id": "kamisato_ayaka",
    "rarity": 5,
    "imagePath": "/character/kamisato_ayaka.png"
  },
  {
    "id": "kamisato_ayato",
    "rarity": 5,
    "imagePath": "/character/kamisato_ayato.png"
  },
  {
    "id": "sucrose",
    "rarity": 4,
    "imagePath": "/character/sucrose.png"
  },
  {
    "id": "shenhe",
    "rarity": 5,
    "imagePath": "/character/shenhe.png"
  },
  {
    "id": "ganyu",
    "rarity": 5,
    "imagePath": "/character/ganyu.png"
  },
  {
    "id": "jean",
    "rarity": 5,
    "imagePath": "/character/jean.png"
  },
  {
    "id": "bennett",
    "rarity": 4,
    "imagePath": "/character/bennett.png"
  },
  {
    "id": "sangonomiya_kokomi",
    "rarity": 5,
    "imagePath": "/character/sangonomiya_kokomi.png"
  },
  {
    "id": "yanfei",
    "rarity": 4,
    "imagePath": "/character/yanfei.png"
  },
  {
    "id": "venti",
    "rarity": 5,
    "imagePath": "/character/venti.png"
  },
  {
    "id": "kaedehara_kazuha",
    "rarity": 5,
    "imagePath": "/character/kaedehara_kazuha.png"
  },
  {
    "id": "sayu",
    "rarity": 4,
    "imagePath": "/character/sayu.png"
  },
  {
    "id": "traveler_anemo",
    "rarity": 5,
    "imagePath": "/character/traveler.png"
  },
  {
    "id": "traveler_electro",
    "rarity": 5,
    "imagePath": "/character/traveler.png"
  },
  {
    "id": "traveler_geo",
    "rarity": 5,
    "imagePath": "/character/traveler.png"
  },
  {
    "id": "thoma",
    "rarity": 4,
    "imagePath": "/character/thoma.png"
  },
  {
    "id": "yoimiya",
    "rarity": 5,
    "imagePath": "/character/yoimiya.png"
  },
  {
    "id": "amber",
    "rarity": 4,
    "imagePath": "/character/amber.png"
  },
  {
    "id": "aloy",
    "rarity": 5,
    "imagePath": "/character/aloy.png"
  },
  {
    "id": "klee",
    "rarity": 5,
    "imagePath": "/character/klee.png"
  },
  {
    "id": "beidou",
    "rarity": 4,
    "imagePath": "/character/beidou.png"
  },
  {
    "id": "keqing",
    "rarity": 5,
    "imagePath": "/character/keqing.png"
  },
  {
    "id": "kaeya",
    "rarity": 4,
    "imagePath": "/character/kaeya.png"
  },
  {
    "id": "ningguang",
    "rarity": 4,
    "imagePath": "/character/ningguang.png"
  },
  {
    "id": "yae_miko",
    "rarity": 5,
    "imagePath": "/character/yae_miko.png"
  },
  {
    "id": "eula",
    "rarity": 5,
    "imagePath": "/character/eula.png"
  },
  {
    "id": "gorou",
    "rarity": 4,
    "imagePath": "/character/gorou.png"
  },
  {
    "id": "yun_jin",
    "rarity": 4,
    "imagePath": "/character/yun_jin.png"
  },
  {
    "id": "kujou_sara",
    "rarity": 4,
    "imagePath": "/character/kujou_sara.png"
  },
  {
    "id": "lisa",
    "rarity": 4,
    "imagePath": "/character/lisa.png"
  },
  {
    "id": "qiqi",
    "rarity": 5,
    "imagePath": "/character/qiqi.png"
  }
];

export const elementResources: ElementResource[] = [
  {
    "name": "Pyro",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/ac3123b42bf631685287e76c8c834a6c_564491877314389852.png",
    "imagePath": "/element/pyro.png"
  },
  {
    "name": "Hydro",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/f54c8f0dae23fced358c28126f220a11_8997562060019157249.png",
    "imagePath": "/element/hydro.png"
  },
  {
    "name": "Dendro",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/bda7c6cf71ea059c6abc086405a7cdd5_1717146848708050949.png",
    "imagePath": "/element/dendro.png"
  },
  {
    "name": "Electro",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/16d344b6abbc369a2db9d46d6f31305b_7144738962629629573.png",
    "imagePath": "/element/electro.png"
  },
  {
    "name": "Anemo",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/6b5c0d861fd1b4791bd602d3e7296598_8700657350379813969.png",
    "imagePath": "/element/anemo.png"
  },
  {
    "name": "Cryo",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/157c22f5fd473d3c1684c6ee981540b6_1601711336893201442.png",
    "imagePath": "/element/cryo.png"
  },
  {
    "name": "Geo",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/9c4cd6e14b87fc262cca36e6d0e9bdb0_1526899214861833594.png",
    "imagePath": "/element/geo.png"
  }
];

export const weaponTypeResources: WeaponTypeResource[] = [
  {
    "name": "Sword",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/eb8602badf0ade7c03650a440d188ce1_4346782947893420142.png",
    "imagePath": "/weapontype/sword.png"
  },
  {
    "name": "Claymore",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/4b65ed8d8fd30705265fa10ee65c8b61_7363045695641018717.png",
    "imagePath": "/weapontype/claymore.png"
  },
  {
    "name": "Bow",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/e38debacfd0147020895322333ea9d2a_4867338674175003782.png",
    "imagePath": "/weapontype/bow.png"
  },
  {
    "name": "Catalyst",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/91c80bbf63e574fc6d6b1cb8563cf8e3_5665224225336557820.png",
    "imagePath": "/weapontype/catalyst.png"
  },
  {
    "name": "Polearm",
    "imageUrl": "https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/03/27/9c0f0c167f2753035b78c0aed9f01b9f_3170160339356492715.png",
    "imagePath": "/weapontype/polearm.png"
  }
];

export const artifacts: ArtifactSetResource[] = [
  {
    "id": "a_day_carved_from_rising_winds",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/a_day_carved_from_rising_winds.png",
      "plume": "/artifact/a_day_carved_from_rising_winds2.png",
      "sands": "/artifact/a_day_carved_from_rising_winds3.png",
      "goblet": "/artifact/a_day_carved_from_rising_winds4.png",
      "circlet": "/artifact/a_day_carved_from_rising_winds5.png"
    }
  },
  {
    "id": "aubade_of_morningstar_and_moon",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/aubade_of_morningstar_and_moon.png",
      "plume": "/artifact/aubade_of_morningstar_and_moon2.png",
      "sands": "/artifact/aubade_of_morningstar_and_moon3.png",
      "goblet": "/artifact/aubade_of_morningstar_and_moon4.png",
      "circlet": "/artifact/aubade_of_morningstar_and_moon5.png"
    }
  },
  {
    "id": "silken_moons_serenade",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/silken_moons_serenade.png",
      "plume": "/artifact/silken_moons_serenade2.png",
      "sands": "/artifact/silken_moons_serenade3.png",
      "goblet": "/artifact/silken_moons_serenade4.png",
      "circlet": "/artifact/silken_moons_serenade5.png"
    }
  },
  {
    "id": "night_of_the_skys_unveiling",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/night_of_the_skys_unveiling.png",
      "plume": "/artifact/night_of_the_skys_unveiling2.png",
      "sands": "/artifact/night_of_the_skys_unveiling3.png",
      "goblet": "/artifact/night_of_the_skys_unveiling4.png",
      "circlet": "/artifact/night_of_the_skys_unveiling5.png"
    }
  },
  {
    "id": "finale_of_the_deep_galleries",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/finale_of_the_deep_galleries.png",
      "plume": "/artifact/finale_of_the_deep_galleries2.png",
      "sands": "/artifact/finale_of_the_deep_galleries3.png",
      "goblet": "/artifact/finale_of_the_deep_galleries4.png",
      "circlet": "/artifact/finale_of_the_deep_galleries5.png"
    }
  },
  {
    "id": "long_nights_oath",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/long_nights_oath.png",
      "plume": "/artifact/long_nights_oath2.png",
      "sands": "/artifact/long_nights_oath3.png",
      "goblet": "/artifact/long_nights_oath4.png",
      "circlet": "/artifact/long_nights_oath5.png"
    }
  },
  {
    "id": "obsidian_codex",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/obsidian_codex.png",
      "plume": "/artifact/obsidian_codex2.png",
      "sands": "/artifact/obsidian_codex3.png",
      "goblet": "/artifact/obsidian_codex4.png",
      "circlet": "/artifact/obsidian_codex5.png"
    }
  },
  {
    "id": "scroll_of_the_hero_of_cinder_city",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/scroll_of_the_hero_of_cinder_city.png",
      "plume": "/artifact/scroll_of_the_hero_of_cinder_city2.png",
      "sands": "/artifact/scroll_of_the_hero_of_cinder_city3.png",
      "goblet": "/artifact/scroll_of_the_hero_of_cinder_city4.png",
      "circlet": "/artifact/scroll_of_the_hero_of_cinder_city5.png"
    }
  },
  {
    "id": "unfinished_reverie",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/unfinished_reverie.png",
      "plume": "/artifact/unfinished_reverie2.png",
      "sands": "/artifact/unfinished_reverie3.png",
      "goblet": "/artifact/unfinished_reverie4.png",
      "circlet": "/artifact/unfinished_reverie5.png"
    }
  },
  {
    "id": "fragment_of_harmonic_whimsy",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/fragment_of_harmonic_whimsy.png",
      "plume": "/artifact/fragment_of_harmonic_whimsy2.png",
      "sands": "/artifact/fragment_of_harmonic_whimsy3.png",
      "goblet": "/artifact/fragment_of_harmonic_whimsy4.png",
      "circlet": "/artifact/fragment_of_harmonic_whimsy5.png"
    }
  },
  {
    "id": "song_of_days_past",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/song_of_days_past.png",
      "plume": "/artifact/song_of_days_past2.png",
      "sands": "/artifact/song_of_days_past3.png",
      "goblet": "/artifact/song_of_days_past4.png",
      "circlet": "/artifact/song_of_days_past5.png"
    }
  },
  {
    "id": "nighttime_whispers_in_the_echoing_woods",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/nighttime_whispers_in_the_echoing_woods.png",
      "plume": "/artifact/nighttime_whispers_in_the_echoing_woods2.png",
      "sands": "/artifact/nighttime_whispers_in_the_echoing_woods3.png",
      "goblet": "/artifact/nighttime_whispers_in_the_echoing_woods4.png",
      "circlet": "/artifact/nighttime_whispers_in_the_echoing_woods5.png"
    }
  },
  {
    "id": "golden_troupe",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/golden_troupe.png",
      "plume": "/artifact/golden_troupe2.png",
      "sands": "/artifact/golden_troupe3.png",
      "goblet": "/artifact/golden_troupe4.png",
      "circlet": "/artifact/golden_troupe5.png"
    }
  },
  {
    "id": "marechaussee_hunter",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/marechaussee_hunter.png",
      "plume": "/artifact/marechaussee_hunter2.png",
      "sands": "/artifact/marechaussee_hunter3.png",
      "goblet": "/artifact/marechaussee_hunter4.png",
      "circlet": "/artifact/marechaussee_hunter5.png"
    }
  },
  {
    "id": "vourukashas_glow",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/vourukashas_glow.png",
      "plume": "/artifact/vourukashas_glow2.png",
      "sands": "/artifact/vourukashas_glow3.png",
      "goblet": "/artifact/vourukashas_glow4.png",
      "circlet": "/artifact/vourukashas_glow5.png"
    }
  },
  {
    "id": "nymphs_dream",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/nymphs_dream.png",
      "plume": "/artifact/nymphs_dream2.png",
      "sands": "/artifact/nymphs_dream3.png",
      "goblet": "/artifact/nymphs_dream4.png",
      "circlet": "/artifact/nymphs_dream5.png"
    }
  },
  {
    "id": "desert_pavilion_chronicle",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/desert_pavilion_chronicle.png",
      "plume": "/artifact/desert_pavilion_chronicle2.png",
      "sands": "/artifact/desert_pavilion_chronicle3.png",
      "goblet": "/artifact/desert_pavilion_chronicle4.png",
      "circlet": "/artifact/desert_pavilion_chronicle5.png"
    }
  },
  {
    "id": "flower_of_paradise_lost",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/flower_of_paradise_lost.png",
      "plume": "/artifact/flower_of_paradise_lost2.png",
      "sands": "/artifact/flower_of_paradise_lost3.png",
      "goblet": "/artifact/flower_of_paradise_lost4.png",
      "circlet": "/artifact/flower_of_paradise_lost5.png"
    }
  },
  {
    "id": "gilded_dreams",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/gilded_dreams.png",
      "plume": "/artifact/gilded_dreams2.png",
      "sands": "/artifact/gilded_dreams3.png",
      "goblet": "/artifact/gilded_dreams4.png",
      "circlet": "/artifact/gilded_dreams5.png"
    }
  },
  {
    "id": "deepwood_memories",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/deepwood_memories.png",
      "plume": "/artifact/deepwood_memories2.png",
      "sands": "/artifact/deepwood_memories3.png",
      "goblet": "/artifact/deepwood_memories4.png",
      "circlet": "/artifact/deepwood_memories5.png"
    }
  },
  {
    "id": "retracing_bolide",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/retracing_bolide.png",
      "plume": "/artifact/retracing_bolide2.png",
      "sands": "/artifact/retracing_bolide3.png",
      "goblet": "/artifact/retracing_bolide4.png",
      "circlet": "/artifact/retracing_bolide5.png"
    }
  },
  {
    "id": "shimenawas_reminiscence",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/shimenawas_reminiscence.png",
      "plume": "/artifact/shimenawas_reminiscence2.png",
      "sands": "/artifact/shimenawas_reminiscence3.png",
      "goblet": "/artifact/shimenawas_reminiscence4.png",
      "circlet": "/artifact/shimenawas_reminiscence5.png"
    }
  },
  {
    "id": "vermillion_hereafter",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/vermillion_hereafter.png",
      "plume": "/artifact/vermillion_hereafter2.png",
      "sands": "/artifact/vermillion_hereafter3.png",
      "goblet": "/artifact/vermillion_hereafter4.png",
      "circlet": "/artifact/vermillion_hereafter5.png"
    }
  },
  {
    "id": "gambler",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/gambler.png",
      "plume": "/artifact/gambler2.png",
      "sands": "/artifact/gambler3.png",
      "goblet": "/artifact/gambler4.png",
      "circlet": "/artifact/gambler5.png"
    }
  },
  {
    "id": "gladiators_finale",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/gladiators_finale.png",
      "plume": "/artifact/gladiators_finale2.png",
      "sands": "/artifact/gladiators_finale3.png",
      "goblet": "/artifact/gladiators_finale4.png",
      "circlet": "/artifact/gladiators_finale5.png"
    }
  },
  {
    "id": "maiden_beloved",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/maiden_beloved.png",
      "plume": "/artifact/maiden_beloved2.png",
      "sands": "/artifact/maiden_beloved3.png",
      "goblet": "/artifact/maiden_beloved4.png",
      "circlet": "/artifact/maiden_beloved5.png"
    }
  },
  {
    "id": "resolution_of_sojourner",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/resolution_of_sojourner.png",
      "plume": "/artifact/resolution_of_sojourner2.png",
      "sands": "/artifact/resolution_of_sojourner3.png",
      "goblet": "/artifact/resolution_of_sojourner4.png",
      "circlet": "/artifact/resolution_of_sojourner5.png"
    }
  },
  {
    "id": "pale_flame",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/pale_flame.png",
      "plume": "/artifact/pale_flame2.png",
      "sands": "/artifact/pale_flame3.png",
      "goblet": "/artifact/pale_flame4.png",
      "circlet": "/artifact/pale_flame5.png"
    }
  },
  {
    "id": "viridescent_venerer",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/viridescent_venerer.png",
      "plume": "/artifact/viridescent_venerer2.png",
      "sands": "/artifact/viridescent_venerer3.png",
      "goblet": "/artifact/viridescent_venerer4.png",
      "circlet": "/artifact/viridescent_venerer5.png"
    }
  },
  {
    "id": "emblem_of_severed_fate",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/emblem_of_severed_fate.png",
      "plume": "/artifact/emblem_of_severed_fate2.png",
      "sands": "/artifact/emblem_of_severed_fate3.png",
      "goblet": "/artifact/emblem_of_severed_fate4.png",
      "circlet": "/artifact/emblem_of_severed_fate5.png"
    }
  },
  {
    "id": "crimson_witch_of_flames",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/crimson_witch_of_flames.png",
      "plume": "/artifact/crimson_witch_of_flames2.png",
      "sands": "/artifact/crimson_witch_of_flames3.png",
      "goblet": "/artifact/crimson_witch_of_flames4.png",
      "circlet": "/artifact/crimson_witch_of_flames5.png"
    }
  },
  {
    "id": "lavawalker",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/lavawalker.png",
      "plume": "/artifact/lavawalker2.png",
      "sands": "/artifact/lavawalker3.png",
      "goblet": "/artifact/lavawalker4.png",
      "circlet": "/artifact/lavawalker5.png"
    }
  },
  {
    "id": "oceanhued_clam",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/oceanhued_clam.png",
      "plume": "/artifact/oceanhued_clam2.png",
      "sands": "/artifact/oceanhued_clam3.png",
      "goblet": "/artifact/oceanhued_clam4.png",
      "circlet": "/artifact/oceanhued_clam5.png"
    }
  },
  {
    "id": "wanderers_troupe",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/wanderers_troupe.png",
      "plume": "/artifact/wanderers_troupe2.png",
      "sands": "/artifact/wanderers_troupe3.png",
      "goblet": "/artifact/wanderers_troupe4.png",
      "circlet": "/artifact/wanderers_troupe5.png"
    }
  },
  {
    "id": "the_exile",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/the_exile.png",
      "plume": "/artifact/the_exile2.png",
      "sands": "/artifact/the_exile3.png",
      "goblet": "/artifact/the_exile4.png",
      "circlet": "/artifact/the_exile5.png"
    }
  },
  {
    "id": "heart_of_depth",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/heart_of_depth.png",
      "plume": "/artifact/heart_of_depth2.png",
      "sands": "/artifact/heart_of_depth3.png",
      "goblet": "/artifact/heart_of_depth4.png",
      "circlet": "/artifact/heart_of_depth5.png"
    }
  },
  {
    "id": "martial_artist",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/martial_artist.png",
      "plume": "/artifact/martial_artist2.png",
      "sands": "/artifact/martial_artist3.png",
      "goblet": "/artifact/martial_artist4.png",
      "circlet": "/artifact/martial_artist5.png"
    }
  },
  {
    "id": "bloodstained_chivalry",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/bloodstained_chivalry.png",
      "plume": "/artifact/bloodstained_chivalry2.png",
      "sands": "/artifact/bloodstained_chivalry3.png",
      "goblet": "/artifact/bloodstained_chivalry4.png",
      "circlet": "/artifact/bloodstained_chivalry5.png"
    }
  },
  {
    "id": "echoes_of_an_offering",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/echoes_of_an_offering.png",
      "plume": "/artifact/echoes_of_an_offering2.png",
      "sands": "/artifact/echoes_of_an_offering3.png",
      "goblet": "/artifact/echoes_of_an_offering4.png",
      "circlet": "/artifact/echoes_of_an_offering5.png"
    }
  },
  {
    "id": "noblesse_oblige",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/noblesse_oblige.png",
      "plume": "/artifact/noblesse_oblige2.png",
      "sands": "/artifact/noblesse_oblige3.png",
      "goblet": "/artifact/noblesse_oblige4.png",
      "circlet": "/artifact/noblesse_oblige5.png"
    }
  },
  {
    "id": "instructor",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/instructor.png",
      "plume": "/artifact/instructor2.png",
      "sands": "/artifact/instructor3.png",
      "goblet": "/artifact/instructor4.png",
      "circlet": "/artifact/instructor5.png"
    }
  },
  {
    "id": "berserker",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/berserker.png",
      "plume": "/artifact/berserker2.png",
      "sands": "/artifact/berserker3.png",
      "goblet": "/artifact/berserker4.png",
      "circlet": "/artifact/berserker5.png"
    }
  },
  {
    "id": "archaic_petra",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/archaic_petra.png",
      "plume": "/artifact/archaic_petra2.png",
      "sands": "/artifact/archaic_petra3.png",
      "goblet": "/artifact/archaic_petra4.png",
      "circlet": "/artifact/archaic_petra5.png"
    }
  },
  {
    "id": "thundersoother",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/thundersoother.png",
      "plume": "/artifact/thundersoother2.png",
      "sands": "/artifact/thundersoother3.png",
      "goblet": "/artifact/thundersoother4.png",
      "circlet": "/artifact/thundersoother5.png"
    }
  },
  {
    "id": "defenders_will",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/defenders_will.png",
      "plume": "/artifact/defenders_will2.png",
      "sands": "/artifact/defenders_will3.png",
      "goblet": "/artifact/defenders_will4.png",
      "circlet": "/artifact/defenders_will5.png"
    }
  },
  {
    "id": "scholar",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/scholar.png",
      "plume": "/artifact/scholar2.png",
      "sands": "/artifact/scholar3.png",
      "goblet": "/artifact/scholar4.png",
      "circlet": "/artifact/scholar5.png"
    }
  },
  {
    "id": "thundering_fury",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/thundering_fury.png",
      "plume": "/artifact/thundering_fury2.png",
      "sands": "/artifact/thundering_fury3.png",
      "goblet": "/artifact/thundering_fury4.png",
      "circlet": "/artifact/thundering_fury5.png"
    }
  },
  {
    "id": "husk_of_opulent_dreams",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/husk_of_opulent_dreams.png",
      "plume": "/artifact/husk_of_opulent_dreams2.png",
      "sands": "/artifact/husk_of_opulent_dreams3.png",
      "goblet": "/artifact/husk_of_opulent_dreams4.png",
      "circlet": "/artifact/husk_of_opulent_dreams5.png"
    }
  },
  {
    "id": "tenacity_of_the_millelith",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/tenacity_of_the_millelith.png",
      "plume": "/artifact/tenacity_of_the_millelith2.png",
      "sands": "/artifact/tenacity_of_the_millelith3.png",
      "goblet": "/artifact/tenacity_of_the_millelith4.png",
      "circlet": "/artifact/tenacity_of_the_millelith5.png"
    }
  },
  {
    "id": "brave_heart",
    "rarity": 4,
    "imagePaths": {
      "flower": "/artifact/brave_heart.png",
      "plume": "/artifact/brave_heart2.png",
      "sands": "/artifact/brave_heart3.png",
      "goblet": "/artifact/brave_heart4.png",
      "circlet": "/artifact/brave_heart5.png"
    }
  },
  {
    "id": "blizzard_strayer",
    "rarity": 5,
    "imagePaths": {
      "flower": "/artifact/blizzard_strayer.png",
      "plume": "/artifact/blizzard_strayer2.png",
      "sands": "/artifact/blizzard_strayer3.png",
      "goblet": "/artifact/blizzard_strayer4.png",
      "circlet": "/artifact/blizzard_strayer5.png"
    }
  }
];

export const artifactHalfSets: ArtifactHalfSet[] = [
  {
    "id": "atk%-18",
    "setIds": [
      "brave_heart",
      "echoes_of_an_offering",
      "resolution_of_sojourner",
      "gladiators_finale",
      "vermillion_hereafter",
      "shimenawas_reminiscence",
      "nighttime_whispers_in_the_echoing_woods",
      "fragment_of_harmonic_whimsy",
      "unfinished_reverie",
      "a_day_carved_from_rising_winds"
    ]
  },
  {
    "id": "em-80",
    "setIds": [
      "instructor",
      "wanderers_troupe",
      "gilded_dreams",
      "flower_of_paradise_lost",
      "night_of_the_skys_unveiling",
      "aubade_of_morningstar_and_moon"
    ]
  },
  {
    "id": "er-20",
    "setIds": [
      "scholar",
      "the_exile",
      "emblem_of_severed_fate",
      "silken_moons_serenade"
    ]
  },
  {
    "id": "heal%-15",
    "setIds": [
      "oceanhued_clam",
      "maiden_beloved",
      "song_of_days_past"
    ]
  },
  {
    "id": "anemo%-15",
    "setIds": [
      "viridescent_venerer",
      "desert_pavilion_chronicle"
    ]
  },
  {
    "id": "cryo%-15",
    "setIds": [
      "blizzard_strayer",
      "finale_of_the_deep_galleries"
    ]
  },
  {
    "id": "def%-30",
    "setIds": [
      "husk_of_opulent_dreams",
      "defenders_will"
    ]
  },
  {
    "id": "hp%-20",
    "setIds": [
      "tenacity_of_the_millelith",
      "vourukashas_glow"
    ]
  },
  {
    "id": "hydro%-15",
    "setIds": [
      "heart_of_depth",
      "nymphs_dream"
    ]
  },
  {
    "id": "na-ca-dmg%-15",
    "setIds": [
      "martial_artist",
      "marechaussee_hunter"
    ]
  },
  {
    "id": "phys%-25",
    "setIds": [
      "bloodstained_chivalry",
      "pale_flame"
    ]
  },
  {
    "id": "skill-dmg%-20",
    "setIds": [
      "gambler",
      "golden_troupe"
    ]
  },
  {
    "id": "burst-dmg%-20",
    "setIds": [
      "noblesse_oblige"
    ]
  },
  {
    "id": "cr-12",
    "setIds": [
      "berserker"
    ]
  },
  {
    "id": "dendro%-15",
    "setIds": [
      "deepwood_memories"
    ]
  },
  {
    "id": "electro%-15",
    "setIds": [
      "thundering_fury"
    ]
  },
  {
    "id": "electro-res-40",
    "setIds": [
      "thundersoother"
    ]
  },
  {
    "id": "geo%-15",
    "setIds": [
      "archaic_petra"
    ]
  },
  {
    "id": "nightsoul-dmg%-15",
    "setIds": [
      "obsidian_codex"
    ]
  },
  {
    "id": "nightsoul-energy-6",
    "setIds": [
      "scroll_of_the_hero_of_cinder_city"
    ]
  },
  {
    "id": "plunge-dmg%-25",
    "setIds": [
      "long_nights_oath"
    ]
  },
  {
    "id": "pyro%-15",
    "setIds": [
      "crimson_witch_of_flames"
    ]
  },
  {
    "id": "pyro-res-40",
    "setIds": [
      "lavawalker"
    ]
  },
  {
    "id": "shield-35",
    "setIds": [
      "retracing_bolide"
    ]
  }
];

export const weapons: WeaponResource[] = [
  {
    "id": "gest_of_the_mighty_wolf",
    "rarity": 5,
    "imagePath": "/weapon/gest_of_the_mighty_wolf.png"
  },
  {
    "id": "nocturnes_curtain_call",
    "rarity": 5,
    "imagePath": "/weapon/nocturnes_curtain_call.png"
  },
  {
    "id": "lightbearing_moonshard",
    "rarity": 5,
    "imagePath": "/weapon/lightbearing_moonshard.png"
  },
  {
    "id": "the_daybreak_chronicles",
    "rarity": 5,
    "imagePath": "/weapon/the_daybreak_chronicles.png"
  },
  {
    "id": "rainbow_serpents_rain_bow",
    "rarity": 4,
    "imagePath": "/weapon/rainbow_serpents_rain_bow.png"
  },
  {
    "id": "athame_artis",
    "rarity": 5,
    "imagePath": "/weapon/athame_artis.png"
  },
  {
    "id": "reliquary_of_truth",
    "rarity": 5,
    "imagePath": "/weapon/reliquary_of_truth.png"
  },
  {
    "id": "dawning_frost",
    "rarity": 4,
    "imagePath": "/weapon/dawning_frost.png"
  },
  {
    "id": "sacrificers_staff",
    "rarity": 4,
    "imagePath": "/weapon/sacrificers_staff.png"
  },
  {
    "id": "bloodsoaked_ruins",
    "rarity": 5,
    "imagePath": "/weapon/bloodsoaked_ruins.png"
  },
  {
    "id": "etherlight_spindlelute",
    "rarity": 4,
    "imagePath": "/weapon/etherlight_spindlelute.png"
  },
  {
    "id": "nightweavers_looking_glass",
    "rarity": 5,
    "imagePath": "/weapon/nightweavers_looking_glass.png"
  },
  {
    "id": "snare_hook",
    "rarity": 4,
    "imagePath": "/weapon/snare_hook.png"
  },
  {
    "id": "blackmarrow_lantern",
    "rarity": 4,
    "imagePath": "/weapon/blackmarrow_lantern.png"
  },
  {
    "id": "prospectors_shovel",
    "rarity": 4,
    "imagePath": "/weapon/prospectors_shovel.png"
  },
  {
    "id": "master_key",
    "rarity": 4,
    "imagePath": "/weapon/master_key.png"
  },
  {
    "id": "moonweavers_dawn",
    "rarity": 4,
    "imagePath": "/weapon/moonweavers_dawn.png"
  },
  {
    "id": "serenitys_call",
    "rarity": 4,
    "imagePath": "/weapon/serenitys_call.png"
  },
  {
    "id": "flameforged_insight",
    "rarity": 4,
    "imagePath": "/weapon/flameforged_insight.png"
  },
  {
    "id": "fractured_halo",
    "rarity": 5,
    "imagePath": "/weapon/fractured_halo.png"
  },
  {
    "id": "azurelight",
    "rarity": 5,
    "imagePath": "/weapon/azurelight.png"
  },
  {
    "id": "sequence_of_solitude",
    "rarity": 4,
    "imagePath": "/weapon/sequence_of_solitude.png"
  },
  {
    "id": "symphonist_of_scents",
    "rarity": 5,
    "imagePath": "/weapon/symphonist_of_scents.png"
  },
  {
    "id": "vivid_notions",
    "rarity": 5,
    "imagePath": "/weapon/vivid_notions.png"
  },
  {
    "id": "tamayuratei_no_ohanashi",
    "rarity": 4,
    "imagePath": "/weapon/tamayuratei_no_ohanashi.png"
  },
  {
    "id": "sunny_morning_sleepin",
    "rarity": 5,
    "imagePath": "/weapon/sunny_morning_sleepin.png"
  },
  {
    "id": "starcallers_watch",
    "rarity": 5,
    "imagePath": "/weapon/starcallers_watch.png"
  },
  {
    "id": "a_thousand_blazing_suns",
    "rarity": 5,
    "imagePath": "/weapon/a_thousand_blazing_suns.png"
  },
  {
    "id": "astral_vultures_crimson_plumage",
    "rarity": 5,
    "imagePath": "/weapon/astral_vultures_crimson_plumage.png"
  },
  {
    "id": "flowerwreathed_feathers",
    "rarity": 4,
    "imagePath": "/weapon/flowerwreathed_feathers.png"
  },
  {
    "id": "waveriding_whirl",
    "rarity": 4,
    "imagePath": "/weapon/waveriding_whirl.png"
  },
  {
    "id": "calamity_of_eshu",
    "rarity": 4,
    "imagePath": "/weapon/calamity_of_eshu.png"
  },
  {
    "id": "mountainbracing_bolt",
    "rarity": 4,
    "imagePath": "/weapon/mountainbracing_bolt.png"
  },
  {
    "id": "fruitful_hook",
    "rarity": 4,
    "imagePath": "/weapon/fruitful_hook.png"
  },
  {
    "id": "peak_patrol_song",
    "rarity": 5,
    "imagePath": "/weapon/peak_patrol_song.png"
  },
  {
    "id": "sturdy_bone",
    "rarity": 4,
    "imagePath": "/weapon/sturdy_bone.png"
  },
  {
    "id": "chain_breaker",
    "rarity": 4,
    "imagePath": "/weapon/chain_breaker.png"
  },
  {
    "id": "ring_of_yaxche",
    "rarity": 4,
    "imagePath": "/weapon/ring_of_yaxche.png"
  },
  {
    "id": "ashgraven_drinking_horn",
    "rarity": 4,
    "imagePath": "/weapon/ashgraven_drinking_horn.png"
  },
  {
    "id": "footprint_of_the_rainbow",
    "rarity": 4,
    "imagePath": "/weapon/footprint_of_the_rainbow.png"
  },
  {
    "id": "earth_shaker",
    "rarity": 4,
    "imagePath": "/weapon/earth_shaker.png"
  },
  {
    "id": "flute_of_ezpitzal",
    "rarity": 4,
    "imagePath": "/weapon/flute_of_ezpitzal.png"
  },
  {
    "id": "surfs_up",
    "rarity": 5,
    "imagePath": "/weapon/surfs_up.png"
  },
  {
    "id": "fang_of_the_mountain_king",
    "rarity": 5,
    "imagePath": "/weapon/fang_of_the_mountain_king.png"
  },
  {
    "id": "lumidouce_elegy",
    "rarity": 5,
    "imagePath": "/weapon/lumidouce_elegy.png"
  },
  {
    "id": "cloudforged",
    "rarity": 4,
    "imagePath": "/weapon/cloudforged.png"
  },
  {
    "id": "absolution",
    "rarity": 5,
    "imagePath": "/weapon/absolution.png"
  },
  {
    "id": "silvershower_heartstrings",
    "rarity": 5,
    "imagePath": "/weapon/silvershower_heartstrings.png"
  },
  {
    "id": "crimson_moons_semblance",
    "rarity": 5,
    "imagePath": "/weapon/crimson_moons_semblance.png"
  },
  {
    "id": "dialogues_of_the_desert_sages",
    "rarity": 4,
    "imagePath": "/weapon/dialogues_of_the_desert_sages.png"
  },
  {
    "id": "uraku_misugiri",
    "rarity": 5,
    "imagePath": "/weapon/uraku_misugiri.png"
  },
  {
    "id": "cranes_echoing_call",
    "rarity": 5,
    "imagePath": "/weapon/cranes_echoing_call.png"
  },
  {
    "id": "ultimate_overlords_mega_magic_sword",
    "rarity": 4,
    "imagePath": "/weapon/ultimate_overlords_mega_magic_sword.png"
  },
  {
    "id": "verdict",
    "rarity": 5,
    "imagePath": "/weapon/verdict.png"
  },
  {
    "id": "sword_of_narzissenkreuz",
    "rarity": 4,
    "imagePath": "/weapon/sword_of_narzissenkreuz.png"
  },
  {
    "id": "splendor_of_tranquil_waters",
    "rarity": 5,
    "imagePath": "/weapon/splendor_of_tranquil_waters.png"
  },
  {
    "id": "cashflow_supervision",
    "rarity": 5,
    "imagePath": "/weapon/cashflow_supervision.png"
  },
  {
    "id": "tome_of_the_eternal_flow",
    "rarity": 5,
    "imagePath": "/weapon/tome_of_the_eternal_flow.png"
  },
  {
    "id": "ballad_of_the_boundless_blue",
    "rarity": 4,
    "imagePath": "/weapon/ballad_of_the_boundless_blue.png"
  },
  {
    "id": "range_gauge",
    "rarity": 4,
    "imagePath": "/weapon/range_gauge.png"
  },
  {
    "id": "prospectors_drill",
    "rarity": 4,
    "imagePath": "/weapon/prospectors_drill.png"
  },
  {
    "id": "portable_power_saw",
    "rarity": 4,
    "imagePath": "/weapon/portable_power_saw.png"
  },
  {
    "id": "the_dockhands_assistant",
    "rarity": 4,
    "imagePath": "/weapon/the_dockhands_assistant.png"
  },
  {
    "id": "sacrificial_jade",
    "rarity": 4,
    "imagePath": "/weapon/sacrificial_jade.png"
  },
  {
    "id": "scion_of_the_blazing_sun",
    "rarity": 4,
    "imagePath": "/weapon/scion_of_the_blazing_sun.png"
  },
  {
    "id": "ballad_of_the_fjords",
    "rarity": 4,
    "imagePath": "/weapon/ballad_of_the_fjords.png"
  },
  {
    "id": "talking_stick",
    "rarity": 4,
    "imagePath": "/weapon/talking_stick.png"
  },
  {
    "id": "wolffang",
    "rarity": 4,
    "imagePath": "/weapon/wolffang.png"
  },
  {
    "id": "fleuve_cendre_ferryman",
    "rarity": 4,
    "imagePath": "/weapon/fleuve_cendre_ferryman.png"
  },
  {
    "id": "flowing_purity",
    "rarity": 4,
    "imagePath": "/weapon/flowing_purity.png"
  },
  {
    "id": "song_of_stillness",
    "rarity": 4,
    "imagePath": "/weapon/song_of_stillness.png"
  },
  {
    "id": "rightful_reward",
    "rarity": 4,
    "imagePath": "/weapon/rightful_reward.png"
  },
  {
    "id": "tidal_shadow",
    "rarity": 4,
    "imagePath": "/weapon/tidal_shadow.png"
  },
  {
    "id": "finale_of_the_deep",
    "rarity": 4,
    "imagePath": "/weapon/finale_of_the_deep.png"
  },
  {
    "id": "the_first_great_magic",
    "rarity": 5,
    "imagePath": "/weapon/the_first_great_magic.png"
  },
  {
    "id": "ibis_piercer",
    "rarity": 4,
    "imagePath": "/weapon/ibis_piercer.png"
  },
  {
    "id": "jadefalls_splendor",
    "rarity": 5,
    "imagePath": "/weapon/jadefalls_splendor.png"
  },
  {
    "id": "beacon_of_the_reed_sea",
    "rarity": 5,
    "imagePath": "/weapon/beacon_of_the_reed_sea.png"
  },
  {
    "id": "mailed_flower",
    "rarity": 4,
    "imagePath": "/weapon/mailed_flower.png"
  },
  {
    "id": "light_of_foliar_incision",
    "rarity": 5,
    "imagePath": "/weapon/light_of_foliar_incision.png"
  },
  {
    "id": "tulaytullahs_remembrance",
    "rarity": 5,
    "imagePath": "/weapon/tulaytullahs_remembrance.png"
  },
  {
    "id": "toukabou_shigure",
    "rarity": 4,
    "imagePath": "/weapon/toukabou_shigure.png"
  },
  {
    "id": "a_thousand_floating_dreams",
    "rarity": 5,
    "imagePath": "/weapon/a_thousand_floating_dreams.png"
  },
  {
    "id": "wandering_evenstar",
    "rarity": 4,
    "imagePath": "/weapon/wandering_evenstar.png"
  },
  {
    "id": "xiphos_moonlight",
    "rarity": 4,
    "imagePath": "/weapon/xiphos_moonlight.png"
  },
  {
    "id": "key_of_khajnisut",
    "rarity": 5,
    "imagePath": "/weapon/key_of_khajnisut.png"
  },
  {
    "id": "staff_of_the_scarlet_sands",
    "rarity": 5,
    "imagePath": "/weapon/staff_of_the_scarlet_sands.png"
  },
  {
    "id": "makhaira_aquamarine",
    "rarity": 4,
    "imagePath": "/weapon/makhaira_aquamarine.png"
  },
  {
    "id": "missive_windspear",
    "rarity": 4,
    "imagePath": "/weapon/missive_windspear.png"
  },
  {
    "id": "forest_regalia",
    "rarity": 4,
    "imagePath": "/weapon/forest_regalia.png"
  },
  {
    "id": "kings_squire",
    "rarity": 4,
    "imagePath": "/weapon/kings_squire.png"
  },
  {
    "id": "fruit_of_fulfillment",
    "rarity": 4,
    "imagePath": "/weapon/fruit_of_fulfillment.png"
  },
  {
    "id": "moonpiercer",
    "rarity": 4,
    "imagePath": "/weapon/moonpiercer.png"
  },
  {
    "id": "sapwood_blade",
    "rarity": 4,
    "imagePath": "/weapon/sapwood_blade.png"
  },
  {
    "id": "end_of_the_line",
    "rarity": 4,
    "imagePath": "/weapon/end_of_the_line.png"
  },
  {
    "id": "hunters_path",
    "rarity": 5,
    "imagePath": "/weapon/hunters_path.png"
  },
  {
    "id": "kagotsurube_isshin",
    "rarity": 4,
    "imagePath": "/weapon/kagotsurube_isshin.png"
  },
  {
    "id": "fading_twilight",
    "rarity": 4,
    "imagePath": "/weapon/fading_twilight.png"
  },
  {
    "id": "aqua_simulacra",
    "rarity": 5,
    "imagePath": "/weapon/aqua_simulacra.png"
  },
  {
    "id": "dragonspine_spear",
    "rarity": 4,
    "imagePath": "/weapon/dragonspine_spear.png"
  },
  {
    "id": "black_tassel",
    "rarity": 3,
    "imagePath": "/weapon/black_tassel.png"
  },
  {
    "id": "blackcliff_longsword",
    "rarity": 4,
    "imagePath": "/weapon/blackcliff_longsword.png"
  },
  {
    "id": "blackcliff_agate",
    "rarity": 4,
    "imagePath": "/weapon/blackcliff_agate.png"
  },
  {
    "id": "blackcliff_slasher",
    "rarity": 4,
    "imagePath": "/weapon/blackcliff_slasher.png"
  },
  {
    "id": "blackcliff_warbow",
    "rarity": 4,
    "imagePath": "/weapon/blackcliff_warbow.png"
  },
  {
    "id": "blackcliff_pole",
    "rarity": 4,
    "imagePath": "/weapon/blackcliff_pole.png"
  },
  {
    "id": "the_black_sword",
    "rarity": 4,
    "imagePath": "/weapon/the_black_sword.png"
  },
  {
    "id": "harbinger_of_dawn",
    "rarity": 3,
    "imagePath": "/weapon/harbinger_of_dawn.png"
  },
  {
    "id": "raven_bow",
    "rarity": 3,
    "imagePath": "/weapon/raven_bow.png"
  },
  {
    "id": "magic_guide",
    "rarity": 3,
    "imagePath": "/weapon/magic_guide.png"
  },
  {
    "id": "thundering_pulse",
    "rarity": 5,
    "imagePath": "/weapon/thundering_pulse.png"
  },
  {
    "id": "skyrider_sword",
    "rarity": 3,
    "imagePath": "/weapon/skyrider_sword.png"
  },
  {
    "id": "skyrider_greatsword",
    "rarity": 3,
    "imagePath": "/weapon/skyrider_greatsword.png"
  },
  {
    "id": "aquila_favonia",
    "rarity": 5,
    "imagePath": "/weapon/aquila_favonia.png"
  },
  {
    "id": "windblume_ode",
    "rarity": 4,
    "imagePath": "/weapon/windblume_ode.png"
  },
  {
    "id": "mistsplitter_reforged",
    "rarity": 5,
    "imagePath": "/weapon/mistsplitter_reforged.png"
  },
  {
    "id": "snowtombed_starsilver",
    "rarity": 4,
    "imagePath": "/weapon/snowtombed_starsilver.png"
  },
  {
    "id": "rainslasher",
    "rarity": 4,
    "imagePath": "/weapon/rainslasher.png"
  },
  {
    "id": "sword_of_descension",
    "rarity": 4,
    "imagePath": "/weapon/sword_of_descension.png"
  },
  {
    "id": "amos_bow",
    "rarity": 5,
    "imagePath": "/weapon/amos_bow.png"
  },
  {
    "id": "iron_sting",
    "rarity": 4,
    "imagePath": "/weapon/iron_sting.png"
  },
  {
    "id": "ferrous_shadow",
    "rarity": 3,
    "imagePath": "/weapon/ferrous_shadow.png"
  },
  {
    "id": "halberd",
    "rarity": 3,
    "imagePath": "/weapon/halberd.png"
  },
  {
    "id": "compound_bow",
    "rarity": 4,
    "imagePath": "/weapon/compound_bow.png"
  },
  {
    "id": "the_bell",
    "rarity": 4,
    "imagePath": "/weapon/the_bell.png"
  },
  {
    "id": "cinnabar_spindle",
    "rarity": 4,
    "imagePath": "/weapon/cinnabar_spindle.png"
  },
  {
    "id": "redhorn_stonethresher",
    "rarity": 5,
    "imagePath": "/weapon/redhorn_stonethresher.png"
  },
  {
    "id": "vortex_vanquisher",
    "rarity": 5,
    "imagePath": "/weapon/vortex_vanquisher.png"
  },
  {
    "id": "prototype_amber",
    "rarity": 4,
    "imagePath": "/weapon/prototype_amber.png"
  },
  {
    "id": "prototype_crescent",
    "rarity": 4,
    "imagePath": "/weapon/prototype_crescent.png"
  },
  {
    "id": "prototype_starglitter",
    "rarity": 4,
    "imagePath": "/weapon/prototype_starglitter.png"
  },
  {
    "id": "prototype_rancour",
    "rarity": 4,
    "imagePath": "/weapon/prototype_rancour.png"
  },
  {
    "id": "prototype_archaic",
    "rarity": 4,
    "imagePath": "/weapon/prototype_archaic.png"
  },
  {
    "id": "oathsworn_eye",
    "rarity": 4,
    "imagePath": "/weapon/oathsworn_eye.png"
  },
  {
    "id": "thrilling_tales_of_dragon_slayers",
    "rarity": 3,
    "imagePath": "/weapon/thrilling_tales_of_dragon_slayers.png"
  },
  {
    "id": "favonius_lance",
    "rarity": 4,
    "imagePath": "/weapon/favonius_lance.png"
  },
  {
    "id": "favonius_codex",
    "rarity": 4,
    "imagePath": "/weapon/favonius_codex.png"
  },
  {
    "id": "favonius_warbow",
    "rarity": 4,
    "imagePath": "/weapon/favonius_warbow.png"
  },
  {
    "id": "favonius_greatsword",
    "rarity": 4,
    "imagePath": "/weapon/favonius_greatsword.png"
  },
  {
    "id": "favonius_sword",
    "rarity": 4,
    "imagePath": "/weapon/favonius_sword.png"
  },
  {
    "id": "luxurious_sealord",
    "rarity": 4,
    "imagePath": "/weapon/luxurious_sealord.png"
  },
  {
    "id": "serpent_spine",
    "rarity": 4,
    "imagePath": "/weapon/serpent_spine.png"
  },
  {
    "id": "engulfing_lightning",
    "rarity": 5,
    "imagePath": "/weapon/engulfing_lightning.png"
  },
  {
    "id": "the_viridescent_hunt",
    "rarity": 4,
    "imagePath": "/weapon/the_viridescent_hunt.png"
  },
  {
    "id": "freedomsworn",
    "rarity": 5,
    "imagePath": "/weapon/freedomsworn.png"
  },
  {
    "id": "festering_desire",
    "rarity": 4,
    "imagePath": "/weapon/festering_desire.png"
  },
  {
    "id": "emerald_orb",
    "rarity": 3,
    "imagePath": "/weapon/emerald_orb.png"
  },
  {
    "id": "the_stringless",
    "rarity": 4,
    "imagePath": "/weapon/the_stringless.png"
  },
  {
    "id": "elegy_for_the_end",
    "rarity": 5,
    "imagePath": "/weapon/elegy_for_the_end.png"
  },
  {
    "id": "the_flute",
    "rarity": 4,
    "imagePath": "/weapon/the_flute.png"
  },
  {
    "id": "sacrificial_fragments",
    "rarity": 4,
    "imagePath": "/weapon/sacrificial_fragments.png"
  },
  {
    "id": "sacrificial_bow",
    "rarity": 4,
    "imagePath": "/weapon/sacrificial_bow.png"
  },
  {
    "id": "sacrificial_greatsword",
    "rarity": 4,
    "imagePath": "/weapon/sacrificial_greatsword.png"
  },
  {
    "id": "sacrificial_sword",
    "rarity": 4,
    "imagePath": "/weapon/sacrificial_sword.png"
  },
  {
    "id": "sharpshooters_oath",
    "rarity": 3,
    "imagePath": "/weapon/sharpshooters_oath.png"
  },
  {
    "id": "kaguras_verity",
    "rarity": 5,
    "imagePath": "/weapon/kaguras_verity.png"
  },
  {
    "id": "primordial_jade_cutter",
    "rarity": 5,
    "imagePath": "/weapon/primordial_jade_cutter.png"
  },
  {
    "id": "hamayumi",
    "rarity": 4,
    "imagePath": "/weapon/hamayumi.png"
  },
  {
    "id": "white_iron_greatsword",
    "rarity": 3,
    "imagePath": "/weapon/white_iron_greatsword.png"
  },
  {
    "id": "hakushin_ring",
    "rarity": 4,
    "imagePath": "/weapon/hakushin_ring.png"
  },
  {
    "id": "white_tassel",
    "rarity": 3,
    "imagePath": "/weapon/white_tassel.png"
  },
  {
    "id": "whiteblind",
    "rarity": 4,
    "imagePath": "/weapon/whiteblind.png"
  },
  {
    "id": "twin_nephrite",
    "rarity": 3,
    "imagePath": "/weapon/twin_nephrite.png"
  },
  {
    "id": "wolfs_gravestone",
    "rarity": 5,
    "imagePath": "/weapon/wolfs_gravestone.png"
  },
  {
    "id": "the_widsith",
    "rarity": 4,
    "imagePath": "/weapon/the_widsith.png"
  },
  {
    "id": "crescent_pike",
    "rarity": 4,
    "imagePath": "/weapon/crescent_pike.png"
  },
  {
    "id": "haran_geppaku_futsu",
    "rarity": 5,
    "imagePath": "/weapon/haran_geppaku_futsu.png"
  },
  {
    "id": "bloodtainted_greatsword",
    "rarity": 3,
    "imagePath": "/weapon/bloodtainted_greatsword.png"
  },
  {
    "id": "katsuragikiri_nagamasa",
    "rarity": 4,
    "imagePath": "/weapon/katsuragikiri_nagamasa.png"
  },
  {
    "id": "song_of_broken_pines",
    "rarity": 5,
    "imagePath": "/weapon/song_of_broken_pines.png"
  },
  {
    "id": "mouuns_moon",
    "rarity": 4,
    "imagePath": "/weapon/mouuns_moon.png"
  },
  {
    "id": "dark_iron_sword",
    "rarity": 3,
    "imagePath": "/weapon/dark_iron_sword.png"
  },
  {
    "id": "the_alley_flash",
    "rarity": 4,
    "imagePath": "/weapon/the_alley_flash.png"
  },
  {
    "id": "wine_and_song",
    "rarity": 4,
    "imagePath": "/weapon/wine_and_song.png"
  },
  {
    "id": "alley_hunter",
    "rarity": 4,
    "imagePath": "/weapon/alley_hunter.png"
  },
  {
    "id": "eye_of_perception",
    "rarity": 4,
    "imagePath": "/weapon/eye_of_perception.png"
  },
  {
    "id": "the_unforged",
    "rarity": 5,
    "imagePath": "/weapon/the_unforged.png"
  },
  {
    "id": "travelers_handy_sword",
    "rarity": 3,
    "imagePath": "/weapon/travelers_handy_sword.png"
  },
  {
    "id": "wavebreakers_fin",
    "rarity": 4,
    "imagePath": "/weapon/wavebreakers_fin.png"
  },
  {
    "id": "summit_shaper",
    "rarity": 5,
    "imagePath": "/weapon/summit_shaper.png"
  },
  {
    "id": "predator",
    "rarity": 4,
    "imagePath": "/weapon/predator.png"
  },
  {
    "id": "staff_of_homa",
    "rarity": 5,
    "imagePath": "/weapon/staff_of_homa.png"
  },
  {
    "id": "akuoumaru",
    "rarity": 4,
    "imagePath": "/weapon/akuoumaru.png"
  },
  {
    "id": "calamity_queller",
    "rarity": 5,
    "imagePath": "/weapon/calamity_queller.png"
  },
  {
    "id": "frostbearer",
    "rarity": 4,
    "imagePath": "/weapon/frostbearer.png"
  },
  {
    "id": "slingshot",
    "rarity": 3,
    "imagePath": "/weapon/slingshot.png"
  },
  {
    "id": "rust",
    "rarity": 4,
    "imagePath": "/weapon/rust.png"
  },
  {
    "id": "otherworldly_story",
    "rarity": 3,
    "imagePath": "/weapon/otherworldly_story.png"
  },
  {
    "id": "mitternachts_waltz",
    "rarity": 4,
    "imagePath": "/weapon/mitternachts_waltz.png"
  },
  {
    "id": "memory_of_dust",
    "rarity": 5,
    "imagePath": "/weapon/memory_of_dust.png"
  },
  {
    "id": "royal_bow",
    "rarity": 4,
    "imagePath": "/weapon/royal_bow.png"
  },
  {
    "id": "royal_longsword",
    "rarity": 4,
    "imagePath": "/weapon/royal_longsword.png"
  },
  {
    "id": "royal_grimoire",
    "rarity": 4,
    "imagePath": "/weapon/royal_grimoire.png"
  },
  {
    "id": "royal_spear",
    "rarity": 4,
    "imagePath": "/weapon/royal_spear.png"
  },
  {
    "id": "royal_greatsword",
    "rarity": 4,
    "imagePath": "/weapon/royal_greatsword.png"
  },
  {
    "id": "skyward_spine",
    "rarity": 5,
    "imagePath": "/weapon/skyward_spine.png"
  },
  {
    "id": "skyward_harp",
    "rarity": 5,
    "imagePath": "/weapon/skyward_harp.png"
  },
  {
    "id": "skyward_atlas",
    "rarity": 5,
    "imagePath": "/weapon/skyward_atlas.png"
  },
  {
    "id": "skyward_blade",
    "rarity": 5,
    "imagePath": "/weapon/skyward_blade.png"
  },
  {
    "id": "skyward_pride",
    "rarity": 5,
    "imagePath": "/weapon/skyward_pride.png"
  },
  {
    "id": "amenoma_kageuchi",
    "rarity": 4,
    "imagePath": "/weapon/amenoma_kageuchi.png"
  },
  {
    "id": "lost_prayer_to_the_sacred_winds",
    "rarity": 5,
    "imagePath": "/weapon/lost_prayer_to_the_sacred_winds.png"
  },
  {
    "id": "dodoco_tales",
    "rarity": 4,
    "imagePath": "/weapon/dodoco_tales.png"
  },
  {
    "id": "kitain_cross_spear",
    "rarity": 4,
    "imagePath": "/weapon/kitain_cross_spear.png"
  },
  {
    "id": "primordial_jade_wingedspear",
    "rarity": 5,
    "imagePath": "/weapon/primordial_jade_wingedspear.png"
  },
  {
    "id": "fillet_blade",
    "rarity": 3,
    "imagePath": "/weapon/fillet_blade.png"
  },
  {
    "id": "recurve_bow",
    "rarity": 3,
    "imagePath": "/weapon/recurve_bow.png"
  },
  {
    "id": "lithic_spear",
    "rarity": 4,
    "imagePath": "/weapon/lithic_spear.png"
  },
  {
    "id": "lithic_blade",
    "rarity": 4,
    "imagePath": "/weapon/lithic_blade.png"
  },
  {
    "id": "lions_roar",
    "rarity": 4,
    "imagePath": "/weapon/lions_roar.png"
  },
  {
    "id": "dragons_bane",
    "rarity": 4,
    "imagePath": "/weapon/dragons_bane.png"
  },
  {
    "id": "solar_pearl",
    "rarity": 4,
    "imagePath": "/weapon/solar_pearl.png"
  },
  {
    "id": "cool_steel",
    "rarity": 3,
    "imagePath": "/weapon/cool_steel.png"
  },
  {
    "id": "deathmatch",
    "rarity": 4,
    "imagePath": "/weapon/deathmatch.png"
  },
  {
    "id": "polar_star",
    "rarity": 5,
    "imagePath": "/weapon/polar_star.png"
  },
  {
    "id": "messenger",
    "rarity": 3,
    "imagePath": "/weapon/messenger.png"
  },
  {
    "id": "debate_club",
    "rarity": 3,
    "imagePath": "/weapon/debate_club.png"
  },
  {
    "id": "everlasting_moonglow",
    "rarity": 5,
    "imagePath": "/weapon/everlasting_moonglow.png"
  },
  {
    "id": "mappa_mare",
    "rarity": 4,
    "imagePath": "/weapon/mappa_mare.png"
  },
  {
    "id": "the_catch",
    "rarity": 4,
    "imagePath": "/weapon/the_catch.png"
  }
];

