// This file is auto-generated by scripts/lunaris.py
// Do not edit this file directly
import type { CharacterResource, WeaponResource } from "./types";

export const betaCharacters: CharacterResource[] = [];
export const betaWeapons: WeaponResource[] = [];
